### ISSUE TITLE
Primal tech stone anvil and tinker tool bug

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#418] opened 2018-01-08 13:53 UTC
When placing a tinkers tool on a primal tech stone anvil by accident it changed my mattock into an unusable tool with zero durability. The tool is changed permanently even after relog it stays.

**Comment by Syltann** [comment] 2018-01-08 13:56
The tool is changed to have zero durability, stone mining level and 1 attack. No matter what material was originally used on the tool.

**Comment by justinrusso** [comment] 2018-01-08 19:14
Dupe of https://github.com/Darkosto/SevTech-Ages/issues/234

**Closed by justinrusso** 2018-01-08 19:14 UTC
Labels: Alpha 10, Bug, Duplicate
