### ISSUE TITLE
Game crashes immediately on loading after Beetween lands gateway spawning.

### ISSUE THREAD

**Issue by Shock2k** [Darkosto/SevTech-Ages#1159] opened 2018-03-31 02:11 UTC
### Before anything else, use the *search* feature! (Did this)
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Issue / Bug
If you're describing a bug, tell us what should happen --> (Game Should Load)
If you're suggesting a change/improvement, tell us how it should work --> (NA)
If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too) -->  (DONE)
If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you) --> (NA)

## Current Behavior
If describing a bug, tell us what happens instead of the expected behavior --> (Game Crashes)
If suggesting a change/improvement, explain the difference from current behavior --> (NA)
## Possible Solution
Uninstall Horsepower pack then reload.

## Steps to Reproduce (for bugs)
 (See Below)

Crash reports
[crash-2018-03-30_18.47.33-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1865104/crash-2018-03-30_18.47.33-client.txt)
[crash-2018-03-30_18.40.41-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1865105/crash-2018-03-30_18.40.41-client.txt)
[crash-2018-03-30_18.16.41-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1865107/crash-2018-03-30_18.16.41-client.txt)

Steps to repo
Generated the wand thing from the dark druids.
Went back to base and put down a tree and right clicked the wand at the tree.  
The Tree/Portal generated but pushed over my engineering devices (windmill, saw, horse devices, etc)
Game crashed within a couple seconds of leaving the tree.

Every time I attempt to start the game, the game will start, but once the chunks start loading in, the game crashes within a few seconds.

## Context

Trying not to loose progress through age 2.

## Your Environment

* Modpack Version: (3.0.3)
* Java Version: Version 8 Update 162 (build 1.8.0_162_b12)
* Launcher Used: Twitch
* Resourcepack Enabled?: Yes (But removed to try and test, still crashed)
* Optifine Installed?: Yes (Yes, but removed to try and test, still crashed)

**Comment by Shock2k** [comment] 2018-04-01 13:50
I was able to fix this issue based on a bug by DerptyDoo.  Removing the Horse power mod and loading without it fixed the issue (you will get an error about registry entries, click yes and continue).  I then had to put "any block (stone for me)" where the horse power devices were (or the game would crash again after reloading).  

I then re-added the horse power pack and the problem was resolved.

**Comment by GoryMoon** [comment] 2018-04-05 01:33
This is a duplicate of #1105

**Comment by artdude543** [comment] 2018-04-24 14:54
Duplicate of #1105

**Closed by artdude543** 2018-04-24 14:54 UTC
