### ISSUE TITLE
arrow recepie doenst show corectly

### ISSUE THREAD

**Issue by Shoji22** [Darkosto/SevTech-Ages#233] opened 2017-11-29 17:08 UTC
the arrow recepie in stage 2 are not showing corectly up im in stage 2 and its shows only feather in the middl.
![2017-11-29_18 05 27](https://user-images.githubusercontent.com/33992639/33388417-33d9c50c-d530-11e7-9bf6-6c7099b05d6f.png)
i mean the first

**Comment by justinrusso** [comment] 2017-12-01 16:31
The recipe still works as intended, but displays weirdly. This I believe was known and fixed in 1.0.5 of RecipeStages. Though, there have been issues with the latest version as well (jaredlll08/RecipeStages#5)

**Comment by justinrusso** [comment] 2017-12-02 03:00
The recipe should be displaying correctly now.

There is now an issue with it not being staged properly, and can be crafted before that point. See #244

**Closed** 2017-12-11 02:10 UTC
Labels: Alpha 8, Bug, Recipe
