### ISSUE TITLE
Fir stairs orientation bug / oversight

### ISSUE THREAD

**Issue by Petkip** [Darkosto/SevTech-Ages#1928] opened 2018-04-18 12:25 UTC
Edit: Also posted it on the traverse github: https://github.com/TraverseTeam/Traverse/issues/11

 
## Issue / Bug

Fir stairs when placed upside down with the back to the east-player looking to the east, afther placing the upside down they turn upright and make the bottum of the block above see true. only happens with the east placement the other three upside down orientations are fine. 

upside down corners are in the wrong orientation.

## Expected Behavior

fir stairs behaving like other stairs

## Steps to Reproduce (for bugs)

1.make a platform few blocks above you
2.face east
3,place fir stair upside down

## Context

was creating a rim under a roof one side isnt beatiful!!!

## Logs

* Client/Server Log: https://gist.github.com/Petkip/8572592f745448f91445eef9d066dfb5
* Crash Log: no crash

## Client Information

* Modpack Version: 3.0.6
* Java Version: jre-x64\1.8.0_25  and jre1.8.0_161 x64, tried both versions normaly play 161
* Launcher Used: twitch

* Memory Allocated: 6.144MB

* Server/LAN/Single Player: single player
* Resourcepack Enabled?: nope
* Optifine Installed?: nope

**Comment by artdude543** [comment] 2018-04-18 12:41
Am I assuming these are the ones from Primal? If so can you post an issue on his repo and link this issue to that :)

**Comment by Petkip** [comment] 2018-04-18 14:53
checked ig and it said traverse tracked them down and i hope its the correct one :P i posted this over there: https://github.com/TraverseTeam/Traverse/issues/11

**Comment by ProfessorProspector** [comment] 2018-04-22 18:14
I'm unable to reproduce this with just Traverse installed. I am pretty sure this is not me, there must be some mod doing some funky stuff with models.

**Comment by Petkip** [comment] 2018-04-23 19:46
The problem is solved with the new version of traverse. i tested with traverse v1.5.0

**Comment by artdude543** [comment] 2018-04-24 22:59
Will be resolved in 3.0.7

**Closed by artdude543** 2018-04-24 22:59 UTC
Labels: Category: Mod, Type: Bug
