### ISSUE TITLE
Water wheel from better with mods recipe doesn't work

### ISSUE THREAD

**Issue by AmishInvader** [Darkosto/SevTech-Ages#880] opened 2018-03-26 11:36 UTC
8 wood blades around a copper gear doesn't produce anything.

Pack 3.0.1

**Comment by TheAdversary808** [comment] 2018-03-26 13:16
i can agree this recipe does not work - Pack 3.0.1

**Comment by Darkosto** [comment] 2018-03-26 18:19
![image](https://user-images.githubusercontent.com/10309699/37924735-b99eaa32-3100-11e8-9b40-3a7ae2c4196b.png)
I cannot reproduce this bug.

**Comment by sharkykh** [comment] 2018-03-26 23:44
@Darkosto 
Perhaps this is related to the copper chest issue players had been experiencing only on servers?

**Comment by artdude543** [comment] 2018-04-08 10:51
This was fixed a while back now. Closing and if you find this to still be an issue on the latest pack please re-open an issue.

**Closed by artdude543** 2018-04-08 10:51 UTC
