### ISSUE TITLE
Visual glitch/bug with torches

### ISSUE THREAD

**Issue by katmac34** [Darkosto/SevTech-Ages#995] opened 2018-03-28 09:00 UTC
i've seen a visual bug after crafting the beneath portal, torches (normal) are starting to randomly appear with the skin of the lit fibre torch. not sure if this is random or others have had this happen.

**Comment by Ragestrike** [comment] 2018-04-06 07:12
also related to my post #1334  i believe

**Comment by artdude543** [comment] 2018-04-24 13:42
I can't reproduce this issue (tried a few worlds to ensure) I think this _could_ be related to the issue with syncing. (Which is fixed in 3.0.7) so if you're still getting the same issue then. Please re-file the issue following the template.

**Closed by artdude543** 2018-04-24 13:42 UTC
