### ISSUE TITLE
Ender Dragon not spawning

### ISSUE THREAD

**Issue by Craken761** [Darkosto/SevTech-Ages#1762] opened 2018-04-12 15:26 UTC
## Issue / Bug
On entering the End, the Ender Dragon does not spawn. 

## Possible Solution

Research indicates that the dragon kill value is set to 1 before entering the end. This causes the ender dragon not to spawn. This value is set the end is generated. 

I have used a NBT editor to set the dragon kill value to 0 before generating the End. Not ideal but a workaround. 

## Steps to Reproduce (for bugs)

1. Unknown cause
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.06
* Java Version:
* Launcher Used:

* Memory Allocated: 8gb

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Dystilled** [comment] 2018-04-12 16:10
#1575

**Comment by artdude543** [comment] 2018-04-12 19:06
Duplicate of above issue closing; please don't create another issue for one which is already open. Also, post additional findings in the comments.

**Closed by artdude543** 2018-04-12 19:06 UTC
