### ISSUE TITLE
Recipe Bug: Lonsdaleite Crystal Unobtainable

### ISSUE THREAD

**Issue by Fatthunder** [Darkosto/SevTech-Ages#2134] opened 2018-04-28 21:34 UTC
## Issue / Bug

Lonsdaleite Crystal from Environmental Tech currently has many recipes it is used in, though it currently cannot be gotten.

I checked the issue track, but was unable to find a previously opened issue.

## Expected Behavior

Lonsdaleite Crystals should be able to be gotten.  By default I believe they come from Tier 1 Resource miners from Environmental Tech.

## Possible Solution

Add Lonsdaleite Crystal to the Environmental Tech Resource miner, or another way to obtain it.

## Steps to Reproduce (for bugs)

1. Check JEI for way to obtain crystals
2. No ways listed
3. Check config for environmental tech
4. Not listed as an obtainable resource

## Context

I am trying to improve my Environmental tech infrastructure, but an unable to craft any of the other upgrades.

## Logs
N/A

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.172
* Launcher Used: Twitch

* Memory Allocated: 8 GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes (Soartex Modded)
* Optifine Installed?: Yes

## Server Information
* Java Version: 1.8.161
* Operating System: Windows Server 2016 R2
* Hoster/Hosting Soultion: N/A
* Sponge (Non-Vanilla Forge) Server?: N/A

**Comment by artdude543** [comment] 2018-04-28 22:06
Duplicate of #1708

**Closed by artdude543** 2018-04-28 22:06 UTC
