### ISSUE TITLE
Issue with Scannable's "Scanner"

### ISSUE THREAD

**Issue by SphynxLoL** [Darkosto/SevTech-Ages#1780] opened 2018-04-13 06:58 UTC
## Issue / Bug

Scannable's "Scanner" does not locate Galacticraft Silicon or Geolosis Beryl (Emerald) with "Rare Ores" module. 

## Expected Behavior
Once the Scanner is unlocked it is far superior to the prospector rods. The Rare and Common Ore Modules are working as intended for all ores/materials EXCEPT Silicon and Beryl

## Possible Solution
Config issue. I'm assuming GC Silicon and the Geolosys Beryl are not under the "ore______" block format since the Scannable config forces any "ore______" blocks that are not specified in the "Common Ores"list into the "Rare Ore" list. 

Extra Info:
Silicon Block Name: tile.basic_block_core.name
Beryl Block Name: Beryl

**Temporary work around: Manually find the ore with a dowsing rod and using the "Scanner Module: Block" on 1 Silicon Ore and 1 Beryl Ore. This will allow you to locate the blocks with the scanner.

## Steps to Reproduce (for bugs)

1. Craft Scanner from Scannable and a dowsing rod.
2. Locate Silicon or Beryl sample.
3. Find the ores with the dowsing rod and use scanner with "Scanner Module: Rare Ores" installed.
4. Notice the ores will not be highlighted.

**Comment by Dystilled** [comment] 2018-04-13 09:40
#908

**Comment by artdude543** [comment] 2018-04-24 15:31
Duplicate of #1780

**Closed by artdude543** 2018-04-24 15:31 UTC
