### ISSUE TITLE
TPS Issue for servers: Too Many Nether Imps!

### ISSUE THREAD

**Issue by djcosmic2** [Darkosto/SevTech-Ages#2099] opened 2018-04-27 07:17 UTC
I have noticed that for some reason in my server, we had over 2000 imps listed, which was causing tick lag due to excessive entity counts. TPS went from 20 to 10 as soon as I entered Nether. Do imps count towards mob cap? Seems like 2000 is a really high number, especially when overworld passives don't nearly have that number combined

**Comment by artdude543** [comment] 2018-04-27 09:49
Duplicate of #1910

**Closed by artdude543** 2018-04-27 09:49 UTC

**Comment by Sorbe** [comment] 2018-05-18 10:33
Per Utasha in the main bug #1910 listed above...

"/kill @e[type=natura:imp]"

Warning: I have not verified this myself.
