### ISSUE TITLE
Rock Crystal Texture

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SevTech-Ages#643] opened 2018-03-12 01:18 UTC
Like the Aquamarine block, the Rock Crystal block is invisible

![2018-03-11_21 17 29](https://user-images.githubusercontent.com/29290246/37261296-c9054c3c-2571-11e8-99dc-7160df6d3ad3.png)

**Comment by justinrusso** [comment] 2018-03-12 06:32
Seems to be the same issue as 624.

I've found a workaround for this. Ideally though we can pass this along to get fixed. I'm not sure who is at fault here.

**Comment by Darkosto** [comment] 2018-03-12 18:18
What the heck is going on with these blocks?! Is it only Content Tweaker? Does it have to do with a resource folder issue?

**Comment by justinrusso** [comment] 2018-03-12 20:07
No one knows.

**Comment by Darkosto** [comment] 2018-03-12 20:24
https://www.youtube.com/watch?v=s88r_q7oufE

**Comment by justinrusso** [comment] 2018-03-12 20:25
Youre full of youtube links today.

**Comment by artdude543** [comment] 2018-03-13 14:07
I've found the issue; looking into a better fix than copying over Vanilla assets. Then I'll speak about the mod to blame :P

**Comment by artdude543** [comment] 2018-03-13 14:57
Okay, so the mod which was causing the issue is `Better with Mods` not completely the mods fault, however. As it's creating a custom CTM for his own things (from what I can see in the code) and the change does not specify the default `minecraft:blocks/stone` texture in the textures array only his own textures.

From then what I can gather when the models/textures are being baked; the CTM is changing the model which in turn when CT is trying to use the stone model references it's loading the model fine but the variant is broken as it's not set to the one BWM had set up. This could be a bug on CTM's side but I don't think so but technically this should be breaking the stone texture itself also but it's not 🤔 

But regardless the fix for now (which is better than copying Vanilla assets) is to overwrite the mcmeta file BWM is creating and putting it in the `resources` folder which will remove the CTM variant BWM is trying to make. It's a break in his texture but it's a small cost to fix the issue.

## Fix/File Details

### Location
`resources\minecraft\textures\blocks\stone.png.mcmeta`

### Contents 
```json
{}
```
This will fix the issue and the stone texture appears again for CT custom stone variants.

### Alternative Contents
This adds the default stone into the array of supported textures for BMW CTM type which fixes the issue and I guess still allow the mods thing to work but I never saw it in the game tbh so no idea how it's supposed to show.

```
{
   "ctm": {
     "ctm_version": 1,
     "type": "bwm_strata",
     "layer": "SOLID",
     "textures": [
	"minecraft:blocks/stone", // Add the default stone as the first texture.
        "minecraft:blocks/stone_1",
        "minecraft:blocks/stone_2"
     ]
   }
}
```

So yeah this was a fun issue to track down and look into fixing. But we have two fixes or we could talk to the developers of CTM or BWM to find out what is truly breaking the base stone model; for references usage. As this only seems to affect anything, not Minecraft trying to use the model/texture for their own needs. It even could be CT doing something odd but I doubt that.

**Comment by artdude543** [comment] 2018-03-13 21:38
That won't fix the issue completely cos of the `stone.mcmeta` file in the mod itself which needs to be removed/changed.

**Comment by primetoxinz** [comment] 2018-03-13 21:39
the mcmeta file should not load as the  `"type": "bwm_strata"` is not registered to the CTM TextureTypeRegistry

**Comment by artdude543** [comment] 2018-03-13 21:41
Have you got a build for me to test in my debug pack?

**Comment by primetoxinz** [comment] 2018-03-13 21:41
http://ci.blamejared.com/job/BetterWithMods/363/

**Comment by artdude543** [comment] 2018-03-13 21:45
Thanks; I still think there is more to this. As the CTM should not break the baked model at all. As other mods which re-use the stone don't seem to be affected to the extent of CT. When I get more time I'll try to debug it further.

**Comment by primetoxinz** [comment] 2018-03-13 21:46
Yeah, just thought it would be best to at least have a bandaid so people aren't seeing through the world

**Comment by artdude543** [comment] 2018-03-13 21:55
Okay so yeah @Darkosto the latest build also fixes the issue, so either or works from the stuff above or the new patch.

I'll re-look at the issue when I get time unless someone else tracks it down.

**Comment by Darkosto** [comment] 2018-03-14 17:29
Hey @MongoTheElder when you're able, can you check this on Beta 3 to make sure it's good in the modpack? :D

**Closed** 2018-03-14 20:44 UTC
Labels: "Interesting", Beta 2, Bug, Investigate Further
