### ISSUE TITLE
[BUG] cant eat carrots or potatos

### ISSUE THREAD

**Issue by ThatGravyboat** [Darkosto/SevTech-Ages#3] opened 2017-08-31 03:07 UTC
skillable wont let me eat carrots or potatos bc of skillable needing farming levels
~Gravy

**Comment by Darkosto** [comment] 2017-08-31 03:08
Duplicate of https://github.com/Darkosto/SevTech-Ages/issues/2

**Closed** 2017-09-08 19:29 UTC
Labels: duplicate
