### ISSUE TITLE
Galacticraft filled Light O2 Tank staging

### ISSUE THREAD

**Issue by Hillage** [Darkosto/SevTech-Ages#2098] opened 2018-04-27 06:01 UTC
## Issue / Bug
Empty Light Oxygen Tank from Galacticraft is staged in age 4. JEI shows filled tank (900) properly, but when the tank is filled through the oxygen compressor, the resulting item is staged to Age 5.

## Expected Behavior
Receive filled Light Oxygen Tank that is properly staged to Age 4.

## Possible Solution
NBT/meta issue in staging?

## Steps to Reproduce (for bugs)
1. Craft empty Light Oxygen Tank
2. Fill via Galacticraft Oxygen Compressor

## Context
Inventory:
![image](https://user-images.githubusercontent.com/26056548/39347020-bf0d696e-49a5-11e8-9da0-d0ae5981a349.png)

JEI:
![image](https://user-images.githubusercontent.com/26056548/39347031-c7479b54-49a5-11e8-9b75-cf2bf49583d3.png)

## Logs
n/a

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch/Native. Yes, it's using the above mentioned java version, not the old packaged vers.
* Memory Allocated: 8G
* Server/LAN/Single Player: Dedi Server, Linux
* Resourcepack Enabled?: Yes - Faithful, restarted since enabling
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_162
* Operating System: Debian
* Hoster/Hosting Soultion: OVH dedi
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by justinrusso** [comment] 2018-04-27 13:06
Looks to be caused by 2 of those specific tanks existing. Extra Planets as well as Galacticraft adds this item.

**Comment by Hillage** [comment] 2018-04-27 23:02
I followed the recipe, it wasn't Unfamiliar until it filled. 100% filled I believe was necessary. Will update shortly when I can test again.

For the record you can still wear it and it works as expected, just drops from hand if you select it in hot bar.

**Comment by Jandakast** [comment] 2018-04-29 03:41
Apparently sometimes when filling a Galacticraft Light Oxygen Tank it will turn into a full Extra Planets Light Oxygen tank. Re-staged all of Extra Planets recipes and several of the items to ensure all Light oxygen tanks are in stage 4. Should be fixed in dev

**Closed** 2018-04-29 03:41 UTC
Labels: Category: Staging, Priority: Medium
