### ISSUE TITLE
Hotbar item name flashes after a block is broken.

### ISSUE THREAD

**Issue by TrisanaShadows** [Darkosto/SevTech-Ages#1084] opened 2018-03-29 22:01 UTC
![hotbarflash](https://user-images.githubusercontent.com/17152787/38115696-6d970fc4-3409-11e8-9407-84af35d3b1a1.gif)
I have absolutely no idea if this is a vanilla thing, or a tinkers thing. But I am just bringing attention to it.
Modpack Version: 3.0.3
Launcher Used: Twitch Launcher
Resourcepack Enabled?: Soartex Fanver
Optifine Installed?: Yes

**Comment by BlakeBr0** [comment] 2018-03-30 04:19
Thats because every time a block is broken the tools nbt updates with the new total block break count. Not sure if theres a way I can prevent this or if it really even matters honestly.

**Comment by artdude543** [comment] 2018-04-24 14:18
This is a Vanilla thing due to the NBT updating it works for pretty much all blocks/items which update if you're holding them. It's not a bug tbh just a minor case for the display. Closing due to not a pack issue but more of a fun Vanilla mechanic.

**Closed by artdude543** 2018-04-24 14:18 UTC
Labels: Type: Bug
