### ISSUE TITLE
crashed when placing a filtered hopper down when using carry on near water wheel

### ISSUE THREAD

**Issue by OranHexthief** [Darkosto/SevTech-Ages#1154] opened 2018-03-31 00:31 UTC
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 * Please search on the [issue track](../) before creating one.
 
## Issue / Bug
crashed when i placed a filtered hopper with soul sand in it down near a water wheel when i was using carry on to move the hopper. it happened twice so i am including both crash reports.
[crash-2018-03-30_20.16.55-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1865045/crash-2018-03-30_20.16.55-server.txt)
[crash-2018-03-30_20.08.16-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1865047/crash-2018-03-30_20.08.16-server.txt)

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Modpack Version:3.0.3
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:no
* Optifine Installed?:no

**Comment by artdude543** [comment] 2018-04-04 01:31
This is fixed in 3.0.4 please update! 😄

**Closed by artdude543** 2018-04-04 01:31 UTC

**Comment by Skullywag** [comment] 2018-04-10 21:27
Just had this in 3.0.4

net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to betterwithmods.common.blocks.mechanical.BlockMechMachines
	at betterwithmods.common.blocks.mechanical.tile.TileEntityFilteredHopper.getBlock(TileEntityFilteredHopper.java:400) ~[TileEntityFilteredHopper.class:?]
	at betterwithmods.common.blocks.mechanical.tile.TileEntityFilteredHopper.func_73660_a(TileEntityFilteredHopper.java:175) ~[TileEntityFilteredHopper.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more

This was when placing it next to a fence post when it has soul sand in it.
