### ISSUE TITLE
Wolves seem confused

### ISSUE THREAD

**Issue by DerpityDoo** [Darkosto/SevTech-Ages#1000] opened 2018-03-28 11:23 UTC
When wolves aggro in a pack and you strike one of them, they seem to have 2 mob AI's fighting each other, one trying to run away, and the other trying to bite your face off. The effect makes them kinda derpy and easy to kill

**Comment by DerpityDoo** [comment] 2018-03-28 11:24
Also, 1000th issue reported :D

**Comment by muskabeatz** [comment] 2018-03-28 13:34
True, i can confirm as well, they sometimes kill animals, and if you hit them, there's a chance of them attacking with their back, not the face (for some reason) or just seem confused and start making circles. 
And i'd also like to say that the wild dogs, sometimes, they just start dragging you towards themselves and it's almost impossible to escape. (I don't know if it was intended)

**Comment by cheesealmighty** [comment] 2018-03-28 17:49
Easy to kill? I find their current AI to be very challenging. Normally mobs just charge into you, so you can easily back off while chop their faces off and hit them back with knockback, so they can't really hit you. 

Now they just attack you, get hit, scamper off, then swarm on you again, like damn furry guerrilla fighters.

**Comment by artdude543** [comment] 2018-04-24 13:37
Closing this as it's not really a valid issue with the pack tbh. Their AI is "fun" and differ to other mobs anyway.

**Closed by artdude543** 2018-04-24 13:37 UTC
