### ISSUE TITLE
[3.0.6] Modular Machines Chemical Mixer hangs game

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1951] opened 2018-04-19 18:38 UTC
## Issue / Bug

Shift-clicking a bucket of Molten Naptha into the tiny fluid input on the chemical mixer causes Minecraft to hang. Not crash, nothing is written to the logs, the client just stops until the OS detects that it's "not responding" and offers to kill it. 

## Expected Behavior

Was trying to fill the input from a bucket. 

## Steps to Reproduce (for bugs)
1. Build Chemical Mixer Modular Machine
2. Open the interface for either of the Fluid Input blocks
3. Shift-click bucket of molten naphta. 

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8_161
* Launcher Used: MultiMC 5 0.6.2

* Memory Allocated: 6GB

* Server/LAN/Single Player: SSP
* Resourcepack Enabled?: N
* Optifine Installed?: N

**Comment by Jandakast** [comment] 2018-04-19 22:09
Cannot Reproduce in Dev. This may be fixed with the Modular Machines update.

**Comment by Targren** [comment] 2018-04-19 23:05
I tried installing the latest version into 3.0.6, but the problem persists. I'll just wait for dev to become Release.

**Comment by Jandakast** [comment] 2018-04-19 23:51
Reported to mod dev 

https://github.com/Nedelosk/Modular-Machines/issues/37

**Comment by Targren** [comment] 2018-04-20 02:51
@Jandakast 

Not to be "that guy", but it's actually HellfirePVP's "[Modular Machinery](https://github.com/HellFirePvP/ModularMachinery/issues)".  You put the issue in the wrong project's tracker. :) 

I'd do it myself, but it would probably be weighted heavier coming from you guys.

**Comment by Targren** [comment] 2018-04-20 18:29
https://github.com/HellFirePvP/ModularMachinery/issues/82

**Comment by Jandakast** [comment] 2018-04-27 23:39
Thanks for being "that guy" and for posting it on the correct issue tracker. @Targren

**Comment by artdude543** [comment] 2018-04-28 23:15
Included in 3.0.7

**Closed by artdude543** 2018-04-28 23:15 UTC
Labels: Status: Reported To Mod, Status: Waiting on Mod Release, Type: Crash
