### ISSUE TITLE
Galacticraft connectivity issues 

### ISSUE THREAD

**Issue by daddy77gaming** [Darkosto/SevTech-Ages#1512] opened 2018-04-06 12:42 UTC
3.0.4

while trying to connect power and liquid transferring to machines like oxygen collector and compressor the issue is the usual sides for power are not working instead BOTH power and fluid only work on (the side with the circle ( usually for fluids )

![2018-04-06_13 37 45](https://user-images.githubusercontent.com/31905330/38421651-1a2020b6-39a8-11e8-8f1c-4b2f0956de15.png)

the power connection visual only work on that square side but does not provide the power

![2018-04-06_13 31 00](https://user-images.githubusercontent.com/31905330/38421721-62d758ba-39a8-11e8-8b83-dd8514b48304.png)

the power connection visual does not connect to the circle ( fluid side ) but DOES provide power

![2018-04-06_13 30 40](https://user-images.githubusercontent.com/31905330/38421764-8feb0afe-39a8-11e8-9d7f-34921163048c.png)

**Comment by artdude543** [comment] 2018-04-06 21:56
Wait what the issue here? That fact your losing energy passive? It's not a bug at all nor an issue. Passive power loss is a thing with a few mods now. You may have created a power loop causing the issue or the power transfer pipes take a loss over blocks also. But I'm closing this as it's not an issue with the pack.

**Closed by artdude543** 2018-04-06 21:56 UTC

**Comment by daddy77gaming** [comment] 2018-04-06 23:09
sorry dude.. but did you READ my post??

power AND fluid ONLY connects to one and the same side making it IMPOSSIBLE to both power and pump fluids out of the machine as it is usual to be able too ( i do not care about power slowly draining  if i dont input power)

So the problem is the fact i cant power the machine and also pull out the resulting fluid

**Comment by daddy77gaming** [comment] 2018-04-06 23:11
power should connect  to the square side and fluid should connect to the round side of galacticraft as it has Always done in other packs i played ( like MSB3 also 1.12 )

**Comment by daddy77gaming** [comment] 2018-04-06 23:51
didnt know you also read closed issues why i made a new one..

![2018-04-07_00 46 07](https://user-images.githubusercontent.com/31905330/38448598-ab4a8f88-3a05-11e8-922c-b361a159e2ba.png)

with GC wires it works..

![2018-04-07_00 16 49](https://user-images.githubusercontent.com/31905330/38448605-ad7b78ee-3a05-11e8-809f-b39bb1102f43.png)

with cyclic it doesnt ( but does work on fluid output side, strangly enough )

![2018-04-07_00 50 07](https://user-images.githubusercontent.com/31905330/38448642-050bb0c4-3a06-11e8-9039-6ec882765418.png)

with IE it also works

So i guess its just an issue with cyclic

**Comment by daddy77gaming** [comment] 2018-04-06 23:53
One thing i did notice is when you jump in a rocket you do not go into 3rd person mode view automaticly.. which might be a real issue for peepz that have never played GC before ( ergo die when crashing on the moon :) bc they dont see / get the message to hold shift to slow down..

**Comment by artdude543** [comment] 2018-04-07 00:04
Yeah, the issue with the rocket is known and a rare case. (But I think that's still being looked into) I've sent the dev of Cyclic a message about the pipe issue. Will report back once I have more information.

**Comment by artdude543** [comment] 2018-04-07 00:05
We'll comment on the other issue for the time being as that one is open :)
