### ISSUE TITLE
version 3.0.6, kicked for timeout on initial connection to server

### ISSUE THREAD

**Issue by ljbingley** [Darkosto/SevTech-Ages#1835] opened 2018-04-14 20:40 UTC
Every time my friend or I connect to our private server it kicks us at least once for timeout. this was not a problem in 3.0.4. Nothing else installed. Can someone walk me through what I need to do to try and locate the issue? 

When i was updating the server files, the server download was bugged so i copied all the files from client side (specifically the ones indicated in the overwrite folder). The issue there is some class not found exception in the FML forge server launch wraper.

**Comment by Espergium** [comment] 2018-04-14 23:39
This is because on first-run, stuff takes a little longer to load and there's a good chance your client can time-out to the multiplayer server. If a server sees your client as "unresponsive" for 30 seconds then it boots you.

Loading a singleplayer world first and connecting to multiplayer will significantly reduce the chance of this happening.

**Comment by aheater18** [comment] 2018-04-14 23:49
I'm having the same issue. My friend managed to join earlier, but now gets kicked right after all his advancements load in (according to his game's logs).

**Comment by JonnaJudin** [comment] 2018-04-16 12:38
We experienced similar timeout issues from the start, only way for us to play any 1.12.x pack is to use this mod which increases the hardcoded timeout value. Maybe it might help. Haven't noticed any issues since adding the mod in the pack.
https://minecraft.curseforge.com/projects/randompatches

**Comment by MissPotato** [comment] 2018-04-18 23:13
We added -Dfml.readTimeout=300 to the server and it's seemed to fix it.

**Comment by Espergium** [comment] 2018-04-19 04:05
Had this issue with another user on another modpack. It seems if the computer can't catch up in about 30 seconds they get timed out. Randompatches increases the initial login timeout to 300 seconds, and the reply interval to 60.

This solved their issue of the player disconnecting while logging in.
Aside, sevtech does take two attempts for me and regardless of single or multiplayer my machine catches up just at the timeout mark. Reconnecting I instantly load in and render everything and this is on an i7-4770k, 4096 RAM allocated, 1080ti hybrid.

When in doubt: Increase the timeout.

**Comment by MissPotato** [comment] 2018-04-19 15:48
There is no harm in it being that high, either, as far as I'm aware - that is. Random Patches def fixed it though.

**Comment by 3jlowes** [comment] 2018-04-23 18:03
I remember watching darkostos stream where he said this was being caused by latest version of scannable mod.

**Comment by artdude543** [comment] 2018-04-24 15:51
Duplicate of #1671

**Closed by artdude543** 2018-04-24 15:51 UTC
