### ISSUE TITLE
Fighting the Ender Dragon

### ISSUE THREAD

**Issue by NattyPew** [Darkosto/SevTech-Ages#1751] opened 2018-04-12 08:28 UTC
I am getting teleported around like crazy as soon as I enter the end. I am completely unable to move on my own and can not even turn around to defend against mobs.

**Comment by TWJedi** [comment] 2018-04-12 08:49
This is caused by the plants in the End by the Primal Core mod. 3.0.5 should have fixed that issue, which version of the pack are you on? 

If you are still having an issue in 3.0.5 or 3.0.6, you can delete the DIM1 folder in your world save folder to regenerate the End dimension.

**Comment by artdude543** [comment] 2018-04-12 19:15
This was fixed in 3.0.5 and in the changelog for the mod (which is also in-game)
`Properly stop teleporting from Ineris plants in the End dimension. May only affect new generation.`

So you may need to regenerate your dimension for the change to take effect. But this issue was fixed and tested in a new generation that's disabled but due to how the mod did the effect current gen may still have the issue which we can't do anything about.

**Closed by artdude543** 2018-04-12 19:15 UTC
