### ISSUE TITLE
Better With Mods Guide Book Spirit Crash

### ISSUE THREAD

**Issue by xBloodxMoonx** [Darkosto/SevTech-Ages#850] opened 2018-03-25 22:33 UTC
## Instruction on how to do issues like your boy darkosto

When you open  the entry about the Spirit in the Better with Mods Manual and click on the image the game  crashes

- Java 1.8.0_25
- Forge 14.23.2.2634
- Minecraft 1.12.2
- SevTech Ages 3.0.1

Latest.log - https://pastebin.com/Su5AVJV9
crash-2018-03-26_00.28.30-client.txt - https://pastebin.com/2HMLFQt1

**Comment by Turkey2349** [comment] 2018-03-25 22:38
Duplicate of #829

**Closed by Turkey2349** 2018-03-25 22:38 UTC
