### ISSUE TITLE
[Bug] Fighting Druids Causes Game To Crash To Desktop

### ISSUE THREAD

**Issue by TibbersTeaParty** [Darkosto/SevTech-Ages#1043] opened 2018-03-28 23:37 UTC
Whilst fighting the Dark Druids in order to get the Swamp Talisman pieces, as the druids are throwing you around it can cause the game to crash to desktop. I've noticed this issue tends to occur more often when you are you being attacked by more than 1 Druid at a time. Here is the pastebin of the crash log. https://pastebin.com/raw/tgBDuEmF.

**Comment by vadis365** [comment] 2018-03-29 12:33
Hello,
The issue may have happened randomly when fighting the druids but it's not the cause this points to BWM.
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at betterwithmods.common.blocks.mechanical.tile.TileEntityWaterwheel.getRenderBoundingBox(TileEntityWaterwheel.java:144)

It's a BWM issue with the water wheel of which I believe is fixed in the next update and fixed in BWM itself. 
Cheers,
Me.

**Comment by vadis365** [comment] 2018-03-29 12:37
Closing as this is a duplicate issue - but it is being dealt with here.
#1049

**Closed by vadis365** 2018-03-29 12:37 UTC
Labels: Duplicate
