### ISSUE TITLE
3.0.5 Crash with Turntable

### ISSUE THREAD

**Issue by AzureMeow** [Darkosto/SevTech-Ages#1544] opened 2018-04-07 06:33 UTC
## Issue / Bug
While using the turntable the game will hard crash after a few item changes.
## Expected Behavior
After placing a block of clay on a turntable a few items will appear and after the jar the game hard crashes.

## Possible Solution
It is possible the item which the urn is meant to change into on the turntable is missing or incorrectly documented.

## Steps to Reproduce (for bugs)
Place a block of clay on a functional turntable and wait.
Block ->Cruciable->Planter->Vase->Urn->##Crash##
               Crash Log
https://pastebin.com/wT6s6Zhx
I have replicated this in multiple creative worlds on all 4 setting of the turntable.

## Context
Since the turntable is active when you load the world it means the game crashes immediately.

## Client Information
* Modpack Version:3.0.5
* Java Version: jre 1.8.0_161
* Launcher Used:Twitch

**Comment by sarcastic6** [comment] 2018-04-07 08:29
This looks like it may be this issue: https://github.com/BetterWithMods/BetterWithMods/issues/837

**Comment by SingleM4lt** [comment] 2018-04-07 11:33
This happened to me as well (3.0.5), eventually forcing me to delete the block with MCEdit since I could no longer load the world (instant crash upon loading the save). Scribbled down some data from MCEdit while deleting it - unfortunately I didn't take a screenshot or anything - if it can be of any help:

Block Name: Unused Block
Internal Name: UNKNOWN_NAME
Block ID: 1040
Block Data: 2

**Comment by tomgrin10** [comment] 2018-04-07 11:35
Happened to me as well, had to revert to a backup to use my world.

**Comment by Darkosto** [comment] 2018-04-07 15:40
For those of you getting this crash, I need a few testers if possible. This script file needs to be inserted into the following location:

minecraft\scripts\mod_integrations

and replace the contents of "better_with_mods.zs" with this: https://pastebin.com/6N2iB4bs

**Comment by tomgrin10** [comment] 2018-04-07 15:50
It's good now, the turntable is not processing the unfamilliar item at all.

**Comment by Darkosto** [comment] 2018-04-07 15:53
Good to know. I'll be putting together a critical update in just a bit here then. I just want to see if I can get a crash fix for Environmental Tech fixed up first.

**Comment by Archan0x** [comment] 2018-04-07 18:06
Confirmed that fixed the problem for me.  After inserting that script I was able to load into my world again.  Thanks!

**Comment by Darkosto** [comment] 2018-04-07 18:07
Cool, 3.0.6 is out with that fix and 2 other tweaks. Thanks for the quick reports. I'm going to close this issue. Please post anything else you happen to find. :)

**Closed by Darkosto** 2018-04-07 18:07 UTC
Labels: Bug, Crash
