### ISSUE TITLE
Mineralis ore distribution.. see the config, but results are totally different

### ISSUE THREAD

**Issue by daddy77gaming** [Darkosto/SevTech-Ages#1374] opened 2018-04-03 22:31 UTC
My setup for some weird reason spawns the weirdest ores, and hardly ANY listed in the config file.
I get all different galacticraft extra planets betweenlands abbysal ores etc.. but no iron,gold  only lapis redstone and coal as vanilla ores

![2018-04-03_23 22 16](https://user-images.githubusercontent.com/31905330/38279081-02bfb89c-379f-11e8-8585-8a543abf55d8.png)

noticed a issue a couple days ago or so #1240

Was anything changed in the regular AS config past that issue and implemented in 3.0.4 that could cause this?

**Comment by justinrusso** [comment] 2018-04-03 23:14
Duplicate of https://github.com/Darkosto/SevTech-Ages/issues/1240

**Closed by justinrusso** 2018-04-03 23:14 UTC
Labels: Duplicate
