### ISSUE TITLE
Betweenlands Crash

### ISSUE THREAD

**Issue by elmatador316** [Darkosto/SevTech-Ages#1541] opened 2018-04-07 05:18 UTC
I'm having the same issue as #1385.  I can get into my world no problem, but when I try to go through the portal for the betweenlands, it starts loading but before the world loads my game crashes.  I updated Java to 161, I updated my Intel and Nvidia drivers to the most recent, and it's still happening.

Pastebin: https://pastebin.com/kxa83EzP

Help!

UPDATE: I updated the pack to 3.0.5 and still have the same issue.

## Client Information
* Modpack Version: 3.0.4
* Java Version: 1.8 Update 161
* Launcher Used:Twitch JAR launcher
* Server/LAN/Single Player:Single Player
* Resourcepack Enabled?:No
* Optifine Installed?:No

**Comment by Pike971** [comment] 2018-04-07 06:33
I am having the exact same issue as above and in issue #1385. I am playing in a Single Player on Pack version 3.0.4. I walk into the portal it begins to load. The load screen switches to The Betweenlands background and then my game crashes. I updated my drivers and Java to 162 and switched the launcher over to Twitch JAR launcher. It still crashed. Here is my crash log as well

[https://pastebin.com/v6eG3fAL](url)

**Comment by TheCyberBrick** [comment] 2018-04-07 10:50
Please try the suggestions under "Mod Notice":
https://bugs.mojang.com/browse/MC-32606

> I updated my Intel and Nvidia drivers to the most recent

Why do you have Nvidia drivers when the game is running on an Intel integrated GPU? Or do actually have a dedicated GPU?

**Comment by TheCyberBrick** [comment] 2018-04-07 14:57
I've made a dev build with a workaround attempt, please try it out and let me know if that fixes the problem for you:
https://github.com/Angry-Pixel/The-Betweenlands-Development-Builds/releases/download/dev-intel-driver-workaround-773-07.04.2018/TheBetweenlands-3.3.6-dev-774-universal.jar

**Comment by elmatador316** [comment] 2018-04-07 15:03
I did see that first link earlier and tried that stuff.  I've dedicated 6G RAM already, and I switched both of the other configs, didn't work.

Where do I put the JAR file?  Just want to make sure I don't put it in the wrong place and it doesn't work because of that

**Comment by TheCyberBrick** [comment] 2018-04-07 15:14
In your Twitch launcher go to your SevTech profile and in the top right there should be a button with 3 dots:
![](https://i.imgur.com/bJwgSkp.png)
Click on that and then click on "Open Folder" (or similar) which should open the profile's folder.
Make a backup of the "saves" folder somewhere, just to be safe.
Next, open the "mods" folder and delete all `.jar` files starting with "TheBetweenlands" and then drop in the dev build (TheBetweenlands-3.3.6-dev-774-universal.jar). That's it!

**Comment by elmatador316** [comment] 2018-04-07 15:29
Still crashed :_(

Pastebin: https://pastebin.com/5zMUiWxn

**Comment by TheCyberBrick** [comment] 2018-04-07 15:54
Aw, ok, thanks. I've got a second test build that is being prepared right now.

> And to answer you earlier question about the Nvidia, I have a seperate Nvidia GPU - GeForce 730M

The game isn't actually using your GPU so you *might* be getting significantly worse performance than what your computer is capable of. This can usually be fixed by adding your Java installation's "javaw.exe" file(s) to the 3D Settings in the Nivida Control Panel. This file can usually be found in
* "C:\Program Files\Java\<jre version>\bin\javaw.exe" and
* "C:\Program Files (x86)\Minecraft\runtime\jre-x64\<jre version>\bin\javaw.exe"
----
I'd be really happy if you could test out one more dev build though before fixing that (because I can't reproduce it with my hardware): https://github.com/Angry-Pixel/The-Betweenlands-Development-Builds/releases/download/dev-intel-driver-workaround-775-07.04.2018/TheBetweenlands-3.3.6-dev-775-universal.jar

**Comment by elmatador316** [comment] 2018-04-07 16:01
Sure thing!  Starting it now.  Thanks for the heads up on the usage of the GPU.  Now it makes a little more sense why games don't play as well as I thought they should on here.

**Comment by elmatador316** [comment] 2018-04-07 16:08
It worked!!!!! Thank you so much!

**Comment by TheCyberBrick** [comment] 2018-04-07 16:15
Alright, great! Now I know at least what causes the driver to give up :P

Once you've fixed the game not using the dedicated GPU you should revert back to the latest official Betweenlands release so that the SevTech profile is back to how it was (https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656)

**Comment by TheCyberBrick** [comment] 2018-04-10 15:18
New update is out that has the workaround

**Comment by vadis365** [comment] 2018-04-25 01:33
Closing because the brick is a boss.

**Closed by vadis365** 2018-04-25 01:33 UTC
Labels: Status: Reported To Mod, Type: Crash
