### ISSUE TITLE
5 sec delay when you open inventory

### ISSUE THREAD

**Issue by r0n1nn** [Darkosto/SevTech-Ages#945] opened 2018-03-27 05:01 UTC
I keep getting a 3-4 sec delay when I open my inventory I don't know what is causing it but I got a java error for you
"internal exception: java.nio.channels.closedchannelexeption"

                                                                                                   hope this helps
                                                                                                                r0n1nn

**Comment by Lumyo** [comment] 2018-03-31 02:22
I have this problem too.
It doesnt happen right after starting the game, and restarting completely minecraft is fixing it for a while.
But the problem always come back

**Comment by Lumyo** [comment] 2018-03-31 13:30
I managed to find how to solve the issue :

Just update Java to the latest version (It worked also for someone else who had the issue)

**Comment by psymonious** [comment] 2018-04-07 09:02
I tried disabling NEI like already mentioned in [#778](https://github.com/Darkosto/SevTech-Ages/issues/778) and that immediately stops the lagging issue.
Enabling it againg brings back the waiting, so it is reproducible.

**Comment by vadis365** [comment] 2018-04-25 00:41
Duplicate of #778

**Closed by vadis365** 2018-04-25 00:41 UTC
