### ISSUE TITLE
Villager Name Discrepancies

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#23] opened 2017-09-01 02:55 UTC
Some of the villagers show one name/job when hovering over them, but a different one when activating a trade. Here are the ones I've found:

- Leatherworker displays as butcher
- Fletcher displays as farmer, shepherd, or fisherman
- Cartographer displays as librarian
- Fisherman displays as fletcher
- Farmer displays as fletcher

![2017-08-31_21 08 13](https://user-images.githubusercontent.com/31498349/29953573-66670d4a-8e9f-11e7-8857-4b817f7fbc2b.png)
![2017-08-31_21 38 22](https://user-images.githubusercontent.com/31498349/29953568-666164e4-8e9f-11e7-99ce-5f94f9d10140.png)
![2017-08-31_21 39 54](https://user-images.githubusercontent.com/31498349/29953569-6662755a-8e9f-11e7-9abc-a5e38442cbb3.png)
![2017-08-31_21 41 39](https://user-images.githubusercontent.com/31498349/29953570-6663adc6-8e9f-11e7-91a9-27bafd79a45a.png)
![2017-08-31_21 41 55](https://user-images.githubusercontent.com/31498349/29953571-6663f574-8e9f-11e7-98c9-98cffb658b3a.png)
![2017-08-31_21 58 06](https://user-images.githubusercontent.com/31498349/29953572-66648638-8e9f-11e7-8c7b-17ff6faf6a9b.png)
![2017-08-31_21 59 00](https://user-images.githubusercontent.com/31498349/29953574-666b38b6-8e9f-11e7-9efd-c95dd65d4476.png)

**Comment by Darkosto** [comment] 2017-09-07 23:38
Definitely a bug, but I'm not too sure on how to fix it yet. I'll dig into more later on. Thanks!

**Comment by Jandakast** [comment] 2017-09-08 04:06
This is an issue with the Neat mod and has been open with no comment or tag since Aug 5, 2016. 

https://github.com/Vazkii/Neat/issues/18

**Comment by codetaylor** [comment] 2017-12-03 20:57
So I traced around in the code a bit and it looks like the issue is caused because the client doesn't have the proper villager career ID. The server sends a packet to tell the client to open the GUI and provides the client with the correct villager name at that time.

My understanding is that entities use the DataManager to sync data with the client. The villager profession is contained in the DataManager and therefore gets synced, however, since the villager career ID is not contained in the DataManager, it doesn't get synced with the client.

This could very well be a vanilla or Forge issue.

**Comment by asiekierka** [comment] 2017-12-22 20:09
Charset 0.5.0's latest build works around it, but the module has to be enabled manually.

It synchronizes careerId from server to client and sets careerLevel to 1 if it's equal to 0 (aka not set), as otherwise populateBuyingList() (which is called by getDisplayName() for some reason I don't understand) will reset careerId to a random one.

**Comment by asiekierka** [comment] 2017-12-22 20:16
Apparently, the correct solution is to run getDisplayName() on the server. Welp.

**Comment by Darkosto** [comment] 2017-12-28 19:02
Yep, so this is going to be fixed by Vazkii to just give villagers the "Villager" name instead of their jobs. It's the best fix that can be done and should work just fine :D

**Closed by Darkosto** 2017-12-28 19:02 UTC
Labels: "Interesting", Bug, Reported To Mod Dev

**Comment by VallenFrostweaver** [comment] 2018-03-22 16:42
I would suggest that if the villager names are not changed (as they are not as of Beta4) to add in both name types into any quest descriptions. For example: On the quest Lost but Now Found: Saying to "Trade for a map from a Cartographer villager" could be changed to "Trade for a map from a Cartographer or Librarian villager" which would allow for either the bug to be fixed or not in the future.
