### ISSUE TITLE
Mixer MK2 and MK3 Blueprints have same recipe

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1680] opened 2018-04-10 03:19 UTC
## Issue / Bug

Mixer MK2 Blueprint
![image](https://user-images.githubusercontent.com/26587049/38534405-17605570-3c4c-11e8-9fe1-bbb29778d614.png)

Mixer MK3 Blueprint
![image](https://user-images.githubusercontent.com/26587049/38534430-3527d4ac-3c4c-11e8-896b-3192781336bc.png)

## Possible Solution
I don't think there's much gameplay content to be added here by having individual recipes, could just make the player craft a Mixer blueprint into a Mixer MK2 Blueprint, into a Mixer MK3 blueprint, or maybe craft it with iron plate for MK2 and then gold plate or something for MK3 to keep it simple.

**Comment by artdude543** [comment] 2018-04-10 15:55
Dupe of #1640

**Closed by artdude543** 2018-04-10 15:55 UTC
Labels: Category: Recipe Conflict, Priority: Medium
