### ISSUE TITLE
Head in backpack bug

### ISSUE THREAD

**Issue by unclekakarot** [Darkosto/SevTech-Ages#1645] opened 2018-04-09 03:23 UTC
## Issue / Bug
Having a player head in an improved backpack's backpack instantly closes the bag when trying to open it

## Steps to Reproduce (for bugs)
1. Get a player head
2. Put player head in Improved backpacks backpack
3. Try and open bag

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_161-b12
* Launcher Used: ATLauncher
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_161-b12
* Operating System: Windows 10
* Hoster/Hosting Soultion: Home computer
* Sponge (Non-Vanilla Forge) Server?: No

**Comment by justinrusso** [comment] 2018-04-09 03:30
Cant replicate this...
![image](https://user-images.githubusercontent.com/25138621/38478125-c1d3d892-3b84-11e8-9aed-8000543ff256.png)

**Comment by unclekakarot** [comment] 2018-04-09 04:06
I think you need to use someone named munchkin604's head. Think that's the name

**Comment by Crotchbat** [comment] 2018-04-10 17:11
I had the same issue, somehow got a MHF_Enderman head. Placed it inside a Stone upgraded Improved Backpack. After that, couldn't open the bag anymore no matter what.
 After opening MCEdit 2.0 I was able to delete the head, bag working as intended again now.
Couldn't find anything that would of caused this, so I don't know how to fix other than MCEdit.
    Modpack Version: 3.0.4 and 3.0.6
    Java Version: 1.8.0.161 (64 Bit)
    Launcher Used: Twitch Launcger
    Server/LAN/Single Player: Single
    Resourcepack Enabled?: No
    Optifine Installed?: Yes

**Comment by artdude543** [comment] 2018-04-25 05:02
Due to being un-reproducible and that most of the involved mods are updated for 3.0.7 going to close this for the being. If it's still an issue after the fact please re-log an issue. Thanks!

**Closed by artdude543** 2018-04-25 05:02 UTC
Labels: Status: Cannot Reproduce
