### ISSUE TITLE
Embers/Carry-on Dupe Bug

### ISSUE THREAD

**Issue by Syltann** [Darkosto/SevTech-Ages#416] opened 2018-01-08 03:51 UTC
The mixer centrifuge from embers can be duped using the carry-on mod by taking the top half of the mixer and placing it separately. After doing this you want to use carry-on once again to pick up the bottom half  and place it back down again.

![2018-01-07_19 49 42](https://user-images.githubusercontent.com/30686588/34658448-167b1ccc-f3e4-11e7-9eed-ba90c8793d09.png)
![2018-01-07_19 49 55](https://user-images.githubusercontent.com/30686588/34658455-1b1332c4-f3e4-11e7-8165-3fccb9b41f76.png)
![2018-01-07_19 50 04](https://user-images.githubusercontent.com/30686588/34658458-1f118a9c-f3e4-11e7-83e3-576113bc8f36.png)

**Comment by justinrusso** [comment] 2018-01-08 08:24
Dupe of https://github.com/Darkosto/SevTech-Ages/issues/403?

**Closed** 2018-01-08 19:20 UTC
Labels: Alpha 10, Duplicate
