### ISSUE TITLE
Game crashes when placing astral sorcery lens

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SevTech-Ages#980] opened 2018-03-28 00:33 UTC
When I interact with the astral sorcery lens my game crashes. I have the starlight crafting table alter set up and I put the lens on the marble pillar and my game crashed. I came back in and tried to link the lens to the table and the game crashed. 

Crash Report - https://pastebin.com/J0zAM45S

## Your Environment
* Modpack Version:3.0.3
* Java Version:1.8.0_161
* Launcher Used:Twitch app
* Resourcepack Enabled?:faithfull
* Optifine Installed?:no

**Comment by artdude543** [comment] 2018-03-28 12:28
Okay this is an issue I've seen before will get this checked out and resolved as soon as we can  :)

**Comment by kugamer** [comment] 2018-04-02 16:24
Still having this issue in 3.0.4 is there a work around? I am not able to use a lot of the utility of Astral Sorcery without the lenses.

**Comment by artdude543** [comment] 2018-04-11 12:53
@kugamer how did you make the lens? Via the AS methods or did you get it spawned in?

**Comment by kugamer** [comment] 2018-04-11 13:51
The first one I made via AS crafting. It disappeared when my game crashed so I cheated another in and it crashed.

**Comment by artdude543** [comment] 2018-04-11 14:11
Yeah, you can't cheat anything really from AS due to the missing NBT data (it relies on). This needs further looking into but it needs fixing somehow.

**Comment by artdude543** [comment] 2018-04-25 02:49
Going to close this as the mod authors could not reproduce the crash. And it's due to missing NBT data but we don't edit the recipe.

If this is still an issue on 3.0.6 and can be reproduced over and over then please re-file so we can work with the devs on the issue to work out what's going on.

**Closed by artdude543** 2018-04-25 02:49 UTC
Labels: Investigate Further, Type: Crash, Version: 3.0.3
