### ISSUE TITLE
crashed shortly after entering nether

### ISSUE THREAD

**Issue by OranHexthief** [Darkosto/SevTech-Ages#1149] opened 2018-03-30 22:27 UTC
## Issue / Bug
went to the nether for the first time and it took a really long time to load up and about 2 min after being in the nether the game crashed. i have 10gig allocated to the pack. restarted and seem to have no issues but i wanted to include the crash report just in case

## Your Environment

* Modpack Version:3.0.3
* Java Version:
* Launcher Used:
* Resourcepack Enabled?:no
* Optifine Installed?:no

[crash-2018-03-30_17.10.36-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1864912/crash-2018-03-30_17.10.36-client.txt)

**Comment by artdude543** [comment] 2018-04-24 13:48
This should have been fixed in 3.0.6 can you update and try again. If the issue is still happening please re-file an issue following the template.

**Closed by artdude543** 2018-04-24 13:48 UTC
