### ISSUE TITLE
 recent bug - cannot make Porcelain now

### ISSUE THREAD

**Issue by Shinystar10967** [Darkosto/SevTech-Ages#1958] opened 2018-04-20 00:27 UTC
Age 0 making melter and heater
## Issue / Bug
 Recently now making porcelain with mill stone grinder you put in bonemeal, clay,and flint it only makes white dye. 

## Expected Behavior
 It supposed to make unfired porcelain

**Comment by artdude543** [comment] 2018-04-20 10:28
This bug was fixed ages ago; please update your pack! Also when you next report an issue please follow the entire template. Otherwise it will be closed, thanks!

**Comment by Shinystar10967** [comment] 2018-04-20 11:08
ok no problem, but it is  up-to date April 7th 2018, and bug must be happening again

**Comment by artdude543** [comment] 2018-04-20 11:42
@DaedalusGame seems this an issue again with the priority checking on the millstone. The recipe is valid in JEI 

![image](https://user-images.githubusercontent.com/1885466/39049178-47f24122-4498-11e8-94c6-f44dfe7132c1.png)

But it's picking the bone meal grind instead.

**Comment by justinrusso** [comment] 2018-04-20 11:44
Please follow the template. The information is useful in helping us.

**Comment by DaedalusGame** [comment] 2018-04-20 12:03
can this be reproduced past the BWM recipe changes

**Comment by Jandakast** [comment] 2018-04-20 23:58
Tested all 6 combinations in Dev with BWM 2.1.11. Reading left to right in the Millstone slots, if Flint is before Bone Meal then it will make porcelain. Otherwise it makes White Dye Powder.

**Comment by CDArena** [comment] 2018-04-21 01:02
^ can confirm that the order of ingredients Can make a difference if the first ingredient is used in another recipe.

**Comment by DaedalusGame** [comment] 2018-04-21 03:09
If the order of ingredients matters this is probably working as intended now.

**Comment by artdude543** [comment] 2018-04-24 22:36
This is resolved in 3.0.7 but telling the user about the order now matters. _(Though not ideal)_ but we hope the tooltip helps.

**Closed by artdude543** 2018-04-24 22:36 UTC
Labels: Type: Bug
