### ISSUE TITLE
3.0.1 to 3.0.2 update issue

### ISSUE THREAD

**Issue by frogger35** [Darkosto/SevTech-Ages#953] opened 2018-03-27 07:51 UTC
I updated my sever and client from 3.0.1 to 3.0.2 and now a lot of blocks say I need to unlock previous stages. Here are pictures of what the blocks say and what my advancement book looks like for age 1. Note I had this all done save for the apple.

![2018-03-27_02 49 33](https://user-images.githubusercontent.com/5314324/37953821-9e267d2a-3169-11e8-8ae8-49fd60a49deb.png)
![2018-03-27_02 49 42](https://user-images.githubusercontent.com/5314324/37953826-a3fc1e9e-3169-11e8-9fa6-c498d83dd075.png)

**Comment by BolSh** [comment] 2018-03-27 09:10
Hey, i got the same problem. do you use together forever?

**Comment by frogger35** [comment] 2018-03-27 09:13
Yes I do use together forever

**Comment by BolSh** [comment] 2018-03-27 09:47
I think there is a problem in there im not sure tho, i've tried everything but nothing seems to work for me

**Comment by frogger35** [comment] 2018-03-27 09:51
I ran the command for the fix of the baykok but with the name found from the /gamestage info @p and it seemed to work kind of. It gave me and others access to some blocks but others were still missing. I also tried crafting the blocks again and the chat message appeared with the icon turning blue but nothing else happened.

**Comment by BolSh** [comment] 2018-03-27 10:07
Even that is not possible for me, i cant delete/add baykok advancement.

**Comment by Thondar** [comment] 2018-03-27 10:55
Got the same issue on my server. Tried to remove the game stages and re-add them.. now i dont have access to any items.

**Comment by artdude543** [comment] 2018-03-27 11:11
I believe something in ItemStages is broken; I've already sent a crash report for another issue to the developer along with a note about the stages being odd. So hopefully he'll get back to us soon.

**Comment by Evylaine** [comment] 2018-03-27 21:00
We don't use the together forever mod, but are also having this problem on my server with the update. Dled the 3.0.1 for now.

**Comment by BolSh** [comment] 2018-03-27 21:01
Update ur together forever mod on both server and client and its fixed

**Comment by Ragestrike** [comment] 2018-03-27 21:04
having same problem. when i /gamestages clear playername, it removed all items from the jei, except meknisum liquids. , i joined another team, and had my stages re-added but JEI is sill only showing mekanism liquids.

**Comment by BolSh** [comment] 2018-03-27 21:04
read my post above

**Comment by artdude543** [comment] 2018-03-27 21:11
Most of these issues mentioned will be fixed in 3.0.3 you'll have to wait for that sadly. Or run commands to give yourself the required stages.

**Comment by Ragestrike** [comment] 2018-03-27 21:35
Can confirm updating together forever fixes it.  togetherforever-1.12.2-1.0.6-12.jar  
thanks BolSh

**Comment by artdude543** [comment] 2018-03-27 21:40
Yes this is part of the next update to the pack along with other major fixes :)

**Comment by LemADEC** [comment] 2018-03-27 22:00
Thanks @Ragestrike for actually providing details to help us

**Comment by artdude543** [comment] 2018-03-27 23:21
Please, can you update to 3.0.3 and confirm is the issue is still persisting thanks!

**Comment by frogger35** [comment] 2018-03-28 06:35
Updating to 3.0.3 did fix this issue.

The second picture posted above remained the same with the addition of the parrot achievement. Gathering the chest, necronomicon, apple, and gem again turned those advancements blue and nothing else needed to be done.

**Closed** 2018-03-28 12:10 UTC
Labels: Bug, Release 3.0.2, Reported To Mod Dev
