### ISSUE TITLE
Better with addons book portaits crashes game

### ISSUE THREAD

**Issue by OranHexthief** [Darkosto/SevTech-Ages#828] opened 2018-03-25 19:39 UTC
### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

when clicking on the karate zombie portait in the better with addons book. the game crashes to launcher

**Comment by Turkey2349** [comment] 2018-03-25 19:44
Can you post a crash log to help us narrow down the cause?

**Comment by artdude543** [comment] 2018-03-28 14:35
This is fixed in 3.0.3

**Closed by artdude543** 2018-03-28 14:35 UTC
