### ISSUE TITLE
Aquaduct source blocks will not automate

### ISSUE THREAD

**Issue by maverickx29** [Darkosto/SevTech-Ages#1955] opened 2018-04-19 21:45 UTC
## Issue / Bug
I can not use aqueduct source blocks for any automated purpose, neither fluid hoppers with a dispenser upgrade, nor fluid pumps from IE work. I'm ok with water not being infinite unless its a river or ocean, but if I aqueduct it in then it should work right?

At this point I'm using a water condensator from IF as it is available to me but it just seems unnecessary.

**Comment by DaedalusGame** [comment] 2018-04-20 02:52
i swear to god fluid pumps should input from aqueducts just fine

**Comment by SeanLatimer** [comment] 2018-04-20 03:29
Make sure you don't put water in the middle block. Let the aqueduct fill it, you'll know cause it looks a little different than a normal source block.

That is actually a tile entity that buildcraft wooden pipes can extract from.

**Comment by maverickx29** [comment] 2018-04-20 04:58
when I put water in the aqueduct block to see if the water collector block is working, it sucks the source block up.

Thank you @SeanLatimer I forgot about good ol' build craft. that works fine off of the aqueduct. I'll let the devs from pneumatic: repressurized and immersive engineering know that their fluid extraction from world doesn't work with aqueducts.

**Comment by CDArena** [comment] 2018-04-21 01:00
Aqueduct water is not a source block or an infintie water block - its basically a water block equivalent to the highest level of flowing vanilla water. It doesn't work for Water wheels either - but you CAN use it to get the water near your water wheel, then stop the aqueduct blocks and just let the water flow 8 more blocks - and THAT water does work for water wheels.

**Comment by DaedalusGame** [comment] 2018-04-21 02:47
Aqueduct Water is not a source block (it doesn't make more sources). It is an infinite water block. Modded pumps should pull water from it if their implementation is not sketchy. Pipes should not connect to the water. (they do currently but I just fixed that) And it does works for water wheels now.

**Comment by artdude543** [comment] 2018-04-24 22:42
Going to close this.  As it's an odd case issue here and I can't reproduce the issue. But if you find this issue to be still in 3.0.7 when it lands. Please report to the mod's own trackers for them to look into the issue at hand.

Thanks!

**Closed by artdude543** 2018-04-24 22:42 UTC
