### ISSUE TITLE
Sigil of Green Grove causing disconnection of server

### ISSUE THREAD

**Issue by TiLath** [Darkosto/SevTech-Ages#1987] opened 2018-04-21 04:22 UTC
## Issue / Bug
I was trying to farm some potatoes with Sigil of Green Grove in a Sigil of holding, few seconds after, I got disconnected from server.

## Steps to Reproduce (for bugs)
1.Put a Sigil of Green Grove in Sigil of Holding 
2.Shift-rightclick to enable it
3.Get disconnected from server

## Logs
* Client/Server Log:https://pastebin.com/KBeScGAn

## Client Information
* Modpack Version:3.0.6
* Java Version:1.8.0_144
* Launcher Used:MultiMC
* Memory Allocated:6GB
* Server/LAN/Single Player:Server
* Resourcepack Enabled?:No
* Optifine Installed?:Yes

## Server Information
* Java Version:1.8.0_161
* Operating System:Windows10
* Hoster/Hosting Soultion:Friend's old computer
* Sponge (Non-Vanilla Forge) Server?:No
* Additional Content Installed?:AromaBackup,Aroma1997core

**Comment by artdude543** [comment] 2018-04-21 11:12
Duplicate of #1557

**Closed by artdude543** 2018-04-21 11:12 UTC
