### ISSUE TITLE
Leads attached to Horse Press occassionally disappear. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#873] opened 2018-03-26 04:21 UTC
### Issue / bug
 - Explain the issue / bug as understandably as possible.
Every now and then when I come back to my base one of the horses I have attached to Horse powered items is missing, usually wandering nearby, no lead in sight. Seems to happen mostly with the Horse Press. 
Leads also seem to glitch out a lot when attaching them to this item. 

 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
Sevtech first public release. 

 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
Cannot be manually recreated that I'm aware of, just need to have a horse attached to the press. 

 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
Not a crash or error. 

 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).
Happens when not near base, not able to attach video.

**Comment by Turmfalke2** [comment] 2018-03-26 19:39
I can confirm this happening, although I felt like it was more a visual bug instead of the lead actual missing.

**Comment by Dystilled** [comment] 2018-03-27 03:15
There is definitely a visual bug component to this at times, But more often than not the horses also detach themselves and wander away.

**Comment by Dystilled** [comment] 2018-03-29 07:58
100% sure that this is to do with the horse press. I'm only seeing the leads break on it, not the other 2 horse powered items. 

Not sure why the topic says I closed this, I never did.

**Comment by extrenix** [comment] 2018-03-30 13:03
I'm bumping this to see if there is a solution?
If I wander away and come back, animals attached with a  lead is always detached :/

**Comment by YURAzz** [comment] 2018-04-04 13:38
Happening with buffalo too, press only, when travelling to other dimensions/walking away

**Comment by CorAxes** [comment] 2018-04-05 02:10
i have this issue with all the horsepower machines on a private server

**Comment by ArbitraryHubris** [comment] 2018-04-05 21:39
I've had it happen on the horse chopper as well, and my horse wandered.  Another player on my server has had horses wander, also.

**Comment by GoryMoon** [comment] 2018-04-05 23:44
All the Horse powered blocks use the same code to attach, I'm using most of the same way as vanilla does but can't do all.
The blocks are loaded before entities and the blocks will try to find the horse they were connected to.
I have heard to similar this issue before but from own testing I haven't been able to reproduce this.
The visual thing with the lead is also a weird thing I haven't been able to reproduce easily and there for not finding a solution. Have done some stuff to try to fix it before but looks like it don't work.

**Comment by AMR2586** [comment] 2018-04-17 01:02
I'm having this problem with all horse devices on a private server.

**Comment by hartror** [comment] 2018-04-21 03:41
We've had this issue with all animals attached via leads to blocks including fences.

**Comment by artdude543** [comment] 2018-04-25 19:44
This is something we can't fix on the modpack side. And Vanilla is known to have the leads vanish. So it's an awkward thing to fix. But they're not massively expensive to re-make.

So I'm going to close this as it's it a multisided issue with both mods and Vanilla (and maybe Forge) but from the pack side we can't really prevent this from happening.

**Closed by artdude543** 2018-04-25 19:44 UTC

**Comment by thetrav** [comment] 2018-04-27 01:46
I know it's closed, but worth mentioning that relocating setups to underground seems to reduce/remove the issue.  
Likely related to the animals having no path to move to beyond the leashes maximum.

Seems like there may be something that can be done if the mob pathing can be accessed / restricted based on being attached to a horse powered dealy?
