### ISSUE TITLE
Crafting Air Sigil Early

### ISSUE THREAD

**Issue by Ravin890** [Darkosto/SevTech-Ages#2246] opened 2018-05-06 23:22 UTC
## Issue / Bug
Air sigil is craftable prior to age 4

## Expected Behavior
Air sigil should be uncraftable prior to proper age

## Possible Solution
Maybe locking the recipe for the reagent could help lock players from being able to craft the sigil

## Steps to Reproduce (for bugs)
1. Craft reagent
2. Place array down
3. Place any type of hopper pointing to the array
4. Place reagent into hopper
5. Click on array with reinforced slate
6. Get sigil crafted.

## Client Information
* Modpack Version: 3.0.6
* Java Version: 1.8.0_171-b11
* Launcher Used: MultiMC
* Memory Allocated: 8 gb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by artdude543** [comment] 2018-05-06 23:25
Duplicate of #2207

**Closed by artdude543** 2018-05-06 23:25 UTC
