### ISSUE TITLE
Infinite? Oil

### ISSUE THREAD

**Issue by Darkbrute2142** [Darkosto/SevTech-Ages#1766] opened 2018-04-12 18:31 UTC
## Issue / Bug

So this is pretty easy to explain, I am currently in Age 3, I had a BC Factory tank full of oil from the IE pumpjack. I broke the tank trying to move it and it shattered into a bunch of "Fragile Oil Shard"  it says from Buildcraft added by Galacticraft Core. Each shard seems to hold 500 mb, however when i place one into the IE Petroleum Distillation Tower it proceeds to fill the entire tank and then at the end only removes 100 mb from the shard.

## Expected Behavior
not to turn 100mb of oil into 24000mb 

## Steps to Reproduce (for bugs)

1. Place a BC Factory tank outside of the Pumpjack.
2. Once filled break the tank.
3. Place one shard with more than 100mb of oil in it into the Distillation tower.
4. ???
5. Profit

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: 
* Launcher Used: Twitch

* Memory Allocated:

* Server/LAN/Single Player: 
* Resourcepack Enabled?: 
* Optifine Installed?: 

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Dystilled** [comment] 2018-04-12 18:38
#1602

**Comment by artdude543** [comment] 2018-04-12 19:07
Duplicate of above issue closing. Don't re-create issues for the same thing...

**Closed by artdude543** 2018-04-12 19:07 UTC
