### ISSUE TITLE
Forestry and Binnes Bee Mods 

### ISSUE THREAD

**Issue by colbyjr** [Darkosto/SevTech-Ages#2115] opened 2018-04-27 23:26 UTC
Hello I relize this pack was designed with certain things to be implemented In certain ways. With that said  changes can effect the overall flow of the pack. seeing how Buildcraft is already in this mudpack would it Be a challenge or ruin the over all flow by adding Forestry and Binnies Mods to the pack without totally ruining it or would it fatally mess up the overall flow and stability. 
thanks this pack would be be even more immersive with those mods introduced properly for my personal tastes.

**Comment by artdude543** [comment] 2018-04-28 00:38
Duplicate of #1417

**Closed by artdude543** 2018-04-28 00:38 UTC

**Comment by artdude543** [comment] 2018-04-29 10:44
The simple answer is yes it's a bad thing. Minecraft is limited to block/item Id's and the pack is nearly at the cap. Adding any more large mods will cause the mapping to change leading to blocks in the game-changing to other ones and/or breaking the world itself.

**Comment by colbyjr** [comment] 2018-04-29 12:37
Thank you artdude, that's all I was asking for thank you for the kind reply.
