### ISSUE TITLE
F9 doesnt show chunk boundaries?

### ISSUE THREAD

**Issue by Baygadosi** [Darkosto/SevTech-Ages#1388] opened 2018-04-04 04:53 UTC
I've been trying to prospect and I can't get the chunk boundaries to show up, not matter how much i mash F9. I've seen it being used and I have tried to change my key bindings, but just cant get them to show.

 
## Issue / Bug

As described above, pressing F9 has not shown chunk boundaries. Maybe I haven't progressed far enough (up to age 2) but it makes prospecting harder then it needs to be. 
## Steps to Reproduce (for bugs)

1. Press F9
2. 

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch Launcher
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No, Default 
* Optifine Installed?: No

**Comment by Baygadosi** [comment] 2018-04-04 06:25
Nah im not. Straight up vanilla minecraft recourse pack.

**Comment by oOMitchOo** [comment] 2018-04-04 13:14
You're a lazy ... something. All those fields from "Instructions on how to do issues..." aren't there to leave them blank. I would recommend to fill them out properly if you want this issue solved.

**Comment by Darkosto** [comment] 2018-04-04 18:11
When posting issues the information requested is not optional especially when we are trying to reproduce your issue. I'm not going to spend time trying to figure this out without all of the information has been filled out.

**Comment by Baygadosi** [comment] 2018-04-04 22:15
I've added what info I can to help. Dunno what else I can add.

**Comment by talonos2** [comment] 2018-04-17 23:45
Probably a duplicate of https://github.com/Darkosto/SevTech-Ages/issues/1470 See if that helps you, @Baygadosi

**Comment by artdude543** [comment] 2018-04-29 13:51
Closing this as it sounds like NEI is disabled as I can't get the issue to show on my instances. Please follow the notes on the linked issue above.

**Closed by artdude543** 2018-04-29 13:51 UTC
Labels: Type: Question
