### ISSUE TITLE
Dire Wolves spawning in a well lit open base. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1884] opened 2018-04-16 07:00 UTC
## Issue / Bug
Constantly find Direwolves inside my base, its an open plan base, floor is wood plank, not a single square of spawnable area (checked f7). 

## Expected Behavior
Dire wolves should not spawn in lit areas as is a hostile mob. 

## Possible Solution
check spawn rules. 

## Steps to Reproduce (for bugs)
??? Have big open well lit base. 

## Context
Hostile mobs should not spawn in "safe" areas. 

## Client Information

* Modpack Version: 0.6
* Java Version: Latest
* Launcher Used: Twitch Java

* Memory Allocated: 12gb

* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes

**Comment by DerpityDoo** [comment] 2018-04-16 15:02
This thread is a duplicate of #1801

**Comment by Dystilled** [comment] 2018-04-16 15:48
Didn't see the duplicate because the other OP doesn't know that multiple wolves are wolves not wolfs.

**Closed** 2018-04-16 15:49 UTC
