### ISSUE TITLE
Fences and ladders, appearing as Planks after zoning back in from other dimension, not updating in all chunks.

### ISSUE THREAD

**Issue by Ragestrike** [Darkosto/SevTech-Ages#1334] opened 2018-04-02 22:51 UTC
## Issue / Bug
Fences and ladders showing as planks for 5 seconds to 1 minute after re-log, (normal behavior?)

When Zoning in from another zone:
30 seconds to indefinite untill some sort of chunk update, after zoning in and out of another dimension (betweenlands  used  for this example.)

To restore them you either break them, place a fence or something near it, or force some kind of chunk update like opening a fence door (updates its current chunk not all the chunks). 

[Also torches are doing the same]

## Current Behavior
![2018-04-02_18 37 19](https://user-images.githubusercontent.com/24786739/38220019-4aae8c7c-36a6-11e8-944a-aebbaddcd0dc.png)
https://i.imgur.com/uAY19x1.jpg
After zone in

![2018-04-02_18 37 26](https://user-images.githubusercontent.com/24786739/38220036-5716cff6-36a6-11e8-9adf-b7b01c856932.png)
https://i.imgur.com/R5Qe9My.jpg
30seconds

![2018-04-02_18 41 48](https://user-images.githubusercontent.com/24786739/38220044-5d0c03ea-36a6-11e8-8c8a-e820874961b1.png)
https://imgur.com/a/Bi6VJ
20minutes and counting.

*Stage *
![2018-04-02_18 58 25](https://user-images.githubusercontent.com/24786739/38220386-dcc45a64-36a7-11e8-84b9-05bf8f0f8b62.png)

* Modpack Version: 3.0.4
* Java Version:1.8.0_161
* Launcher Used: twitch, Jar.
* Resourcepack Enabled?:no (happened in soartex fanver as well though)
* Optifine Installed?: no

**Comment by Ragestrike** [comment] 2018-04-02 23:28
I think i found the solution, buy changing the Better Fps default settings. standby testing.

**Comment by Ragestrike** [comment] 2018-04-02 23:38
so issue occurs when you use riven "half" algorithm   and is solved with riven "full" algorithm

**Comment by justinrusso** [comment] 2018-04-02 23:54
Was your TPS in general low?

**Comment by Ragestrike** [comment] 2018-04-03 00:08
i havent noticed, it just was updating chunks slowly , and some chunks not at all , now it  updates them all rather fast.

**Comment by Ragestrike** [comment] 2018-04-04 21:25
heres my tps. 
![2018-04-04_15 03 41](https://user-images.githubusercontent.com/24786739/38328661-76e5c30e-3819-11e8-83d1-33db9c63721e.png)

**Comment by Aedda** [comment] 2018-04-15 03:58
Had the same thing when logging out and logging back into a world in only 1 chunk. Seemed to resolve on its own after some time, didn't reoccur.

**Comment by artdude543** [comment] 2018-04-24 13:46
This is mostly fixed in 3.0.7 after we found the mod causing the timeout issue, which will help with the syncing time between world -> client. Going to close this and tag as completed for the next release, however, if the issue is still happening in the next update. Please re-report so using the template so we have fresh data/information to go on to try and work out what's what.

**Closed by artdude543** 2018-04-24 13:46 UTC
