### ISSUE TITLE
Oil duplication bug

### ISSUE THREAD

**Issue by Archan0x** [Darkosto/SevTech-Ages#2118] opened 2018-04-28 01:58 UTC
Upon breaking one of the BC factory tanks when it has oil in it, it will drop oil shards.  If you place one of these shards in the in the bucket input slot of a distillation tower it will completely fill the tower with oil.  In my testing, if I take a 500mb/500mb shard and place it in the bucket input slot and then leave the UI and go back in, it will have filled the tower.

Steps:
[https://imgur.com/a/0alTCKI](https://imgur.com/a/0alTCKI)

Base modpack with no other extra mods installed

**Comment by Dutchs** [comment] 2018-04-28 02:33
duplicate of: #1602

**Comment by artdude543** [comment] 2018-04-28 02:36
Duplicate of #1602

**Closed by artdude543** 2018-04-28 02:36 UTC
