### ISSUE TITLE
Dupe Water Bucket in Automated User

### ISSUE THREAD

**Issue by xolowirth** [Darkosto/SevTech-Ages#1617] opened 2018-04-08 13:37 UTC
## Issue / Bug
Automated User From Cyclic Dupes Water buckets if the filled bucket is in Input used on a Fluid Tank from Inductive Logistics.

## Expected Behavior
Should not work or should try to place water into tank.

## Steps to Reproduce (for bugs)
User Automated user to make water buckets on Fluid Tank. Normal Empty Bucket in input works fine.
But Testing this, I placed a Filled Bucket into the input to see what would happen, this is when it duped.

Setup:
![image](https://user-images.githubusercontent.com/38183932/38468183-997450a8-3b10-11e8-8d8a-6664210f9e0d.png)

Bug. One Water bucket to Two for free.
![image](https://user-images.githubusercontent.com/38183932/38468187-a32cf97e-3b10-11e8-9b25-5984d9e11b20.png)

It will only dupe once. Then if you take a water bucket out of the input, it will dupe again. Requires Manual Intervention.

## Context
Make bucket to water bucket recipe for AE. But tested water bucket in input and this is when it duped.

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.131
* Launcher Used: Twitch

* Server/LAN/Single Player: Single
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by PrinceOfAmber** [comment] 2018-04-18 03:48
I will test again once cyclic 1.14.9 is out, possible duplicate of https://github.com/PrinceOfAmber/Cyclic/issues/778

**Comment by artdude543** [comment] 2018-04-25 05:05
This is fixed in 3.0.7

**Closed by artdude543** 2018-04-25 05:05 UTC
