### ISSUE TITLE
my game Crashes in startup. seems issue with Chisel.

### ISSUE THREAD

**Issue by deanec64** [Darkosto/SevTech-Ages#1693] opened 2018-04-10 14:37 UTC
https://pastebin.com/8516Gh2D
Default install 

it seems that theres an error with 1 of the files for chisel. unsure what to do. 

specifically, it seems that its this error that shows the issue. 

"net.minecraft.client.renderer.StitcherException: Unable to fit: chisel:blocks/cobblestone/layers - size: 16x16 - Maybe try a lowerresolution resourcepack?"

**Comment by artdude543** [comment] 2018-04-10 15:46
Dupe of #924

**Closed by artdude543** 2018-04-10 15:46 UTC

**Comment by justinrusso** [comment] 2018-04-10 16:56
That .. doesnt change a thing. this isnt related to the launcher.
