### ISSUE TITLE
Hunting Dimension Death Loop

### ISSUE THREAD

**Issue by Phantum** [Darkosto/SevTech-Ages#1542] opened 2018-04-07 05:36 UTC
## Issue / Bug

Upon dying in the hunting world, now every time I return there, I spawn ~30 blocks in the air, and drop to my death, every, single time.

https://puu.sh/zXXKZ/a86f35120f.png

https://clips.twitch.tv/PeppyBetterMelonArsonNoSexy

## Expected Behavior
Go through the portal, and not turn into a maple syrup pancake D:

## Possible Solution
Unknown at this point.

## Steps to Reproduce (for bugs)
1. Go into hunting Dimension, attract no less than 4 demon cats, have them kill you by portal
2. Return through portal, into death!  

Can't guarantee this will replicate the bug.

## Context
It made me feel real bad, cause I was hungry for some enderpearl.

## Client Information
* Modpack Version: 3.0.4
* Java Version: 8U161
* Launcher Used: Twitch App

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Fanver Soartex (clientside Only)
* Optifine Installed?: Nope.

## Server Information
* Java Version: Open JDK:8-JRE
* Operating System: Linux 
* Hoster/Hosting Soultion: NodeCraft
* Sponge (Non-Vanilla Forge) Server?: Nope

Contact Information if more required:
fallensungaming@gmail.com
or 
Twitter: SaintPhantum

**Comment by darkhax** [comment] 2018-04-07 07:24
This should be fixed in version 3.0.5 of the pack. Duplicate of https://github.com/Darkosto/SevTech-Ages/issues/1287

**Comment by Phantum** [comment] 2018-04-07 07:41
Ah I skimmed through that one partially, but upon my skim didn't seem the same, I'll update shortly, thanks Darkhax! :)

**Comment by Darkosto** [comment] 2018-04-07 16:00
When you can, please confirm if this is fixed for you in the update :)

**Comment by Phantum** [comment] 2018-04-07 20:27
do you want me to check with the 3.0.6 or 5 version?

**Comment by Phantum** [comment] 2018-04-07 21:56
Confirmed fixed, went through the portal, intentionally died ( D: )  and went through again, no issues

**Closed** 2018-05-05 20:14 UTC
Labels: Version: Outdated
