### ISSUE TITLE
Disable Auto Fisher Since Fishing Loot Tables are Removed

### ISSUE THREAD

**Issue by Vyraal1** [Darkosto/SevTech-Ages#1179] opened 2018-03-31 14:49 UTC
## Issue / Bug
- fishing loot tables are removed via a LootTableTweaker script making the Cyclic fishing net (and other auto fishers useless)

## Your Environment

* Modpack Version: 3.0.3

**Comment by cheesealmighty** [comment] 2018-04-01 10:26
Duplicate of #1122

**Comment by Darkosto** [comment] 2018-04-02 23:10
Removed, thanks!

**Closed by Darkosto** 2018-04-02 23:10 UTC
