### ISSUE TITLE
StitcherException crash

### ISSUE THREAD

**Issue by jdsi1** [Darkosto/SevTech-Ages#924] opened 2018-03-26 23:41 UTC
###Crashing using SevTech all versions
 - Mysterious Bug that just showed up after playing 12 hours of the pack
 -
![issue](https://user-images.githubusercontent.com/37818590/37938829-b572bade-312d-11e8-9230-4e1fae1ec715.PNG)

**Comment by artdude543** [comment] 2018-03-26 23:48
Can you pastebin your client log please!

**Comment by jdsi1** [comment] 2018-03-26 23:54
My client wont let me view my crash report....

**Comment by justinrusso** [comment] 2018-03-26 23:59
I've run into this a lot during development but no one else has mentioned it ever.

Here is one of the crashes: https://gist.github.com/justinrusso/e67f02ec1a18a4af370d0b3f21f204ca

**Comment by jdsi1** [comment] 2018-03-27 00:07
Alright I don't know what any of that means so I will just wait for a solution

**Comment by kragnoth** [comment] 2018-03-27 01:14
Could this be due to the fact that you are using the native launcher, which is using a massively outdated minecraft version?  IE seems to have quite a few bugs if you are using java 8 25. Maybe try running with the jar launcher by going into twitch settings and changing to jar launcher, and loading latest version.

Just a suggestion, but that looks GUI related on the arc furnace, and alot of the GUI issues are due to the massively outdated version of java that mojang uses in their sandboxed native launcher.

**Comment by wyndman** [comment] 2018-03-27 01:16
Your client is having issues rendering block from the chisel mod, if you're using a texture pack try loading it without one.  Justinrusso is having similar issues from the looks of it, the IE stuff has had odd texture crashes since 1.10, best to report it to the IE author as well. You might be able to MCedit out the block if it continues to crash you.

**Comment by jdsi1** [comment] 2018-03-27 01:28
I was able to fix this issue because I was not using my dedicated graphics card. But I am now getting this issue - 
![issue 2](https://user-images.githubusercontent.com/37818590/37941535-9cb2a43c-313c-11e8-8994-a4140d202327.PNG)

**Comment by justinrusso** [comment] 2018-03-28 21:36
@wyndman this isnt just IE though. theres many mods that do it, and is unrelated to one specific mod. IT eventually bogs down and I need to restart, its been the only "fix".

**Comment by WildFTW** [comment] 2018-04-11 19:17
Try allocate more ram to the pack. But this issue has been around for years, I've seen reports of this being an issue all the way back to 2013, with people saying it could be optifine version not being compatible with forge versions to the computer not being able to run 64bit java. To turning the max memory setting for 32bit to 1500M. To be honest this issue seems to be nearly impossible to fix no one has seem to have found a way to fix this. I hope this helps.

**Comment by cjm721** [comment] 2018-04-11 19:29
This issue stems from having to many mods that all load textures. Most textures have to be loaded into a single texture map (for performance reasons). During pack load is when the entire texture map is loaded. The max size of this texture map is determined by your [graphics hardware ](http://feedback.wildfiregames.com/report/opengl/feature/GL_MAX_TEXTURE_SIZE). This is why switching from your CPU graphics to the dedicated fixed it as the dedicated one has a larger max texture size.

There are some possible solutions for this issue for others that run into it:
- Use a lower resolution texture pack (You can find texture packs with lower resolution then the vanilla one)
- Overloaded has high res dynamic textures that you can limit the size of. In Overloaded config turn down:
  - **maxTextureWidth** This one controls the compressed blocks max texture size, it will have the most impact.
  - **blockResolution** This one effects all the standard blocks in the mod
  - **multiArmorResolution** This one effects the armor / multi tool

There are other mods that use lots of the texture map but Overloaded you can change how much you allow it to use just by changing those config values.

Your horsepower crash is unrelated to the first.

**Comment by Jandakast** [comment] 2018-04-11 19:47
This is NOT a pack specific issue. The issue is actually related to the number of textures in the pack and the amount of GPU RAM that is needed to load/handle the textures. Texture Stitching crashes are generally related to running out of RAM for GPU functions, and is separate from the ram you dedicate to Java/Minecraft. Some things to try.

- If you have a dedicated GPU make sure that java is using the Dedicated GPU and not the integrated GPU
- Try using a lower resolution texture pack or no texture pack at all
- Although very rare, it could also be related to a corrupt texture file.  If it is this, then it could be resolved by downloading a fresh instance of the pack and moving your save to it

If the Horsepower crash is not a `net.minecraft.client.renderer.StitcherException` we will need a crash log and it needs to be opened as a new issue to be properly tracked. Thank you

**Closed by Jandakast** 2018-04-11 19:47 UTC
Labels: Type: Bug, Type: Crash

**Comment by justinrusso** [comment] 2018-04-11 20:26
Interesting... why would it be that it just suddenly happens after many game restarts?

In addition, when I close out of my browser, it begins to load past that point again for a while, then refuses to work again until my pc is restarted.

Ive been pack deving like this for months... rinse and repeat the process

**Comment by cjm721** [comment] 2018-04-11 20:50
The original issue was about 100% crash on load. 

If you are having a similar issue intermittently it is most likely a compounding of several causes. Especially since you mentioned closing other programs had an effect.
