### ISSUE TITLE
End Dragon does not spawn- breaks progression completely. 

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1575] opened 2018-04-07 17:42 UTC
Searched for "end" "the end" "end dragon" "dragon
 
## Issue / Bug
End Dragon does not spawn when entering the end. 

## Expected Behavior
End dragon should spawn

## Possible Solution
Make some way to get end crystals to vanilla spawn it/find conflict causing the issue. 

## Steps to Reproduce (for bugs)
Go to the end via end portal in stronghold. 

## Context
Cannot progress at all as end Ores do not spawn

## Client Information

* Modpack Version: 0.5
* Java Version: Latest
* Launcher Used: Twitch Java
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: Soartex
* Optifine Installed?: Yes.

**Comment by Darkosto** [comment] 2018-04-07 20:14
Cannot reproduce. I've had no problem getting him to spawn when testing this out.

**Comment by Darkosto** [comment] 2018-04-07 20:36
Just opened an instance up and went to the end:

https://i.artdude.uk/darkosto/IzDqIuUj.mp4

**Comment by zahlost** [comment] 2018-04-07 22:24
I'm having the same issue. I went to the end but no ender dragon spawned. 
Modpack version: 0.5

Latest java
Twitch launcher
SP
no resourcepack

**Comment by Flickofdawrist** [comment] 2018-04-07 23:30
Same problem with latest 3.0.6 modpack version. World was created on 3.0.4 and I just got to end and there is no dragon.

**Comment by mckibbon17** [comment] 2018-04-08 02:59
I am also getting the same issue with the end not spawning the dragon.

**Comment by futileohm** [comment] 2018-04-08 04:08
The end dragon didn't spawn for me either.

**Comment by Dystilled** [comment] 2018-04-08 04:27
A number of people in the discord have also confirmed this as an issue. 

Is there any chance it's to do with naturally spawning portals rather than creatived in ones? Dunno if thats possible

**Comment by Dystilled** [comment] 2018-04-08 04:40
Yep, my DragonKilled and PreviouslyKilled was also set to 1... Something odd there.

**Comment by harmjan94** [comment] 2018-04-08 18:55
I got my own dedicated server and got the same problem. I manually spawned the enderdragon in and the ores appeared but there's no End portal/portal to the end cities. The achievement also doesn't trigger. How can I solve this on a server?

**Comment by justinrusso** [comment] 2018-04-08 18:58
@harmjan94 likely the same way other users have stated. Editing the level.dat file and setting DragonKilled to 0

**Comment by harmjan94** [comment] 2018-04-08 18:59
In my server files?

**Comment by justinrusso** [comment] 2018-04-08 18:59
Also, if you read the advancement, it states that you need to mine the Biotite and then create Ender Alloy.

**Comment by mckibbon17** [comment] 2018-04-08 19:00
Flickofdawrist  has the fix for it you will have to do what he said with the server files edit the values delete that dim and go back in and it will be spawned

**Comment by Deadnoz** [comment] 2018-04-08 21:49
@darkosto recreating it from the wrong age doesnt mean its unreproducible. because alot of our dragon kill counts were at 1. It means one of the ages was moving it to 1, and what you discovered is it wasnt the tutorial age.

**Comment by justinrusso** [comment] 2018-04-08 21:51
@Deadnoz I'm in the world with all stages and all advancements and it works fine. Stages, nor any advancement, triggers that change.

**Comment by Deadnoz** [comment] 2018-04-08 22:35
@justinrusso considering this thread has a small few, and a lot of people in streams are curious about the issue, Just because you are fine, doesn't mean the issue is resolved sadly. Besides that, darkosto replied in stream and i understand it a bit more.

**Comment by justinrusso** [comment] 2018-04-08 22:46
@Deadnoz Im not sure what youre going on about. Neither I or Darkosto have said this issue is resolved. It would be closed if so.

**Comment by Muddr** [comment] 2018-04-09 02:16
Be interesting to see what versions the worlds were created in, that are having the issue.  Mine is from 3.0.0 (MP moved later to SP) and I have both `DragonKilled` and `PreviouslyKilled` set to 1. 

I copied the world and jumped into stage 4 and went to the end and no dragon spawned. Doing `Save and Quit` while in the end and then coming back into the world will show the boss bar for a second and then it goes away.  I did `/gchouston` back to the overworld, left,  and then set `DragonKilled` and `PreviouslyKilled` to 0. went back to the end and the dragon was there. 

I tried creating a 3.0.6 world and giving myself items to follow the advancements to where I'm at a now (going into dimensions, killing bosses, etc) and I can't reproduce it now.  So might have been a side effect of an old version.

**Comment by Dystilled** [comment] 2018-04-09 05:00
My world was from the day of release.

**Comment by DerpityDoo** [comment] 2018-04-09 09:51
My world was created in 3.0.1 and also had DragonKilled and PreviouslyKilled set to 1. Perhaps this was fixed in a later update unknowingly. Would be worth installing a few different versions of the pack to see if this is the case.

**Comment by sarcastic6** [comment] 2018-04-10 03:10
I think you guys might be barking up the wrong tree with this DragonKilled/PreviouslyKilled thing:

- Create a new Minecraft instance and install Forge and only Forge.
- Create a world, quit before you go to The End.
- Examine level.dat, you'll see that DragonKilled and PreviouslyKilled are both 1.
- Travel to The End, notice that the dragon does in fact spawn
- Re-examine level.dat, and you'll see that DragonKilled and PreviouslyKilled are now both set to 0.

Based on the above, I don't think the fact that those values are 1 if you've never been to The End has any significance.

**Comment by Dystilled** [comment] 2018-04-10 08:55
However, setting those settings to zero fixes the issue. 

If what you've posted is correct, what it indicates to me is that entering the end for the first time is supposed to trigger a reset of the values from 1 to 0 to spawn the dragon, but something is preventing that.

**Comment by benstrathdee** [comment] 2018-04-11 05:12
Just to add to the data here, I also experienced the issue

Modpack Version: 3.0.6
Java Version: 161 64bit
Launcher Used: Twitch launching Jar launcher
Server/LAN/Single Player: SP, opened to LAN a few times, but no other players
World created in 3.0.0

Interestingly, saving + quitting while in The End and reloading the world (not closing the game completely though), causes the End Dragon's Boss Bar to appear on screen briefly upon load, but it disappears shortly afterwards.
Ultimately I used NBTExplorer to set both DragonKilled and PreviouslyKilled to 0 (were set to 1 as others had noted). I did not need to delete any Dimension data, after loading the world again (still in The End) the Dragon was now present.

**Comment by Rixxaw** [comment] 2018-04-11 17:30
Button just had it happen on his stream.  Maybe one of the boss mobs that we kill along the way is setting dragon kill to 1 ?

**Comment by Tommassino** [comment] 2018-04-12 20:17
I have ran into this issue aswell. Played this pack since 3.0.3 and now at 3.0.6 when I arrived into the End the Dragon does not spawn.

**Comment by DaedalusGame** [comment] 2018-04-13 00:13
Heyo, we had a poke at the relevant code and I think this is caused by a mod loading the End, then immediently unloading it before the world can tick once. I'm not sure which mod would do that, but chunk pregeneration thingies are a good shot. I'm trying to wrap my head around the dragon fight code right now to see if i can get some proper data

**Comment by Jandakast** [comment] 2018-04-13 03:32
This is in fact a Forge issue. Any worlds created in Vanilla 1.12.2 or prior to Forge 2647 have the `dragonKilled` and `previouslyKilled` flags set to true which cause the changes made in Forge 2651 for dimensional teleportation to incorrectly ignore the scanForLegacyFight flag. Which makes the game think the Ender Dragon has already been killed. 

There is a Pull request in to forge that should address this issue.
https://github.com/MinecraftForge/MinecraftForge/pull/4868

The Fix, as @DaedalusGame mentioned, would be to roll Forge back to 2650 until Forge releases a version that incorporates the fix.

**Comment by mezz** [comment] 2018-04-15 04:00
This has been fixed in Forge 1.12.2 - 14.23.3.2666

**Comment by DaedalusGame** [comment] 2018-04-15 07:09
666 oh boy...

**Comment by MrHrulgin** [comment] 2018-04-16 07:48
For anyone following this saga, despite this problem being fixed in Forge 1.12.2 - 14.23.3.2666, attempting to use that version will cause an immediate crash upon starting minecraft using SevTech 3.0.6. For me, sitting in the End without an Ender Dragon, rolling Forge back to 2650 worked perfectly, and an ender dragon appeared as soon as I opened the game back up.

**Comment by tjsd** [comment] 2018-04-16 12:13
3.0.6 is not compatible with higher forge versions because of other mods. This will be fixed in 3.0.7

**Comment by Darkosto** [comment] 2018-04-17 16:50
Locking this post. The answer has already been given and comments after this point are not needed.

**Comment by justinrusso** [comment] 2018-04-21 03:01
For anyone interested in a temporary fix by downgrading forge: https://github.com/Darkosto/SevTech-Ages/issues/1981

**Closed** 2018-04-21 03:01 UTC
Labels: Category: Mod, Priority: Critical, Status: Completed, Type: Bug
