### ISSUE TITLE
Crashing to desktop

### ISSUE THREAD

**Issue by Arkene** [Darkosto/SevTech-Ages#1726] opened 2018-04-11 13:34 UTC
## Issue / Bug
Game is crashing to desktop, reporting the following error: 
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float

Server is reporting: 
[Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Arkenite lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

This has happed to at least 3 of us on the server, 2 of us in a team in age 3, the third in age 2.

## Expected Behavior
be able to play the game without crashingt o desktop and then having to watch the logo have a fit while it reloads the mods

## Possible Solution
find the bit of code expecting a float and tell it to expect a integer instead and then if necessary, convert it into a float.

## Steps to Reproduce (for bugs)
1 load minecraft with the Sevtech mods
2 join server
3 crash to desktop. 

## Context
I connected to the server quite happily, ran around a bit, farmed up some celestrial crystals, used the dust to start another batch. cleaned out the astral sorcery stuff from my inventory to make space for more crystals as we were running low. Headed back towards the house to drop off everything i didn't need for more space for  rocks, about half way back, while walking passed a NPC village my screen goes blue and i crash to desktop. with the above error message being told to me by the launcher. reloading the game, i'm dropping out not long after clicking connect and without seeing the game world. 

## Logs

* Client/Server Log: [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Arkenite lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
* Crash Log: 
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float

## Client Information

* Modpack Version: 3.0.6
* Java Version: 1.8.0_161
* Launcher Used: Twitch

* Memory Allocated: 7gb+

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: only what has come with sevtech
* Optifine Installed?: No

## Server Information
* Java Version: unknown, not my server
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment] 2018-04-11 14:12
I need the entire log; Can you Gist or Pastebin it, please. Giving a single line is not useful at all.

**Comment by Arkene** [comment] 2018-04-11 14:29
It was too big toput into one file so i've split it. 

https://pastebin.com/Xf7SSg93  - part 1
https://pastebin.com/RJsKjaeD - part 2

**Comment by artdude543** [comment] 2018-04-11 14:33
Cool thanks logged with the mod developer https://github.com/Mrbysco/JustARaftMod/issues/5

**Comment by Mrbysco** [comment] 2018-04-11 16:57
The strange part is. It should never get an integer.

**Comment by Mrbysco** [comment] 2018-04-11 18:20
I'm unable to reproduce it

**Comment by Mrbysco** [comment] 2018-04-11 18:25
I've also changed some bits of my Entity as I forgot to override some stuff. Will make a build and release it to Curse. (1.1.2)

**Comment by Mrbysco** [comment] 2018-04-11 18:25
Gonna test first if it will mess up existing worlds or not. It shouldn't but I wanna be sure

**Comment by artdude543** [comment] 2018-04-11 18:27
Okay, thanks!

**Comment by Mrbysco** [comment] 2018-04-11 19:01
I've tested the build on my private server and it didn't break my existing rafts. So it should be fine.

**Comment by Mrbysco** [comment] 2018-04-11 19:16
1.1.2 is live on curseforge. But as I'm unable to reproduce the issue the only people that can are the people that have the issue @Arkene

**Comment by Arkene** [comment] 2018-04-12 21:08
Thanks. I'll let you know if it starts happening again.

**Comment by Arkene** [comment] 2018-04-13 15:15
Thanks. I'll let you know if it starts happening again.

**Comment by Mrbysco** [comment] 2018-04-13 18:33
It's live on curse again.

**Comment by Calgor** [comment] 2018-04-17 18:52
Just as an update, I'm one of the other players on the server that @Arkene is on and experienced the same issue with the same error text, crash log available on request from a few days ago. Weirdly enough there were no reported rafts on the server whatsoever and kicked me out mid game which does lead me to question whether it's a red herring. Was actually riding a horse through a biome, passed under a tree into water and couldn't reconnect.

The old "reboot the server" tactic seems to have done the trick to let me connect and our server admin has also updated with the beta from Curse and also applying client side. Will update if any further crashes occur.

**Comment by artdude543** [comment] 2018-04-22 01:53
We have an update of the mod which adds additional checks for this odd issue so would be resolved in the next update 3.0.7

**Closed by artdude543** 2018-04-22 01:53 UTC
Labels: Status: Completed, Status: Reported To Mod, Type: Crash
