### ISSUE TITLE
I have the Player Grave in my inventory.

### ISSUE THREAD

**Issue by Lanapeed** [Darkosto/SevTech-Ages#1839] opened 2018-04-14 22:42 UTC
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment] 2018-04-14 23:24
We are aware the issue also dupe of #1066 also grats on using the issue template. Next time you report an issue fill all the details in! Otherwise, it will be ignored thanks!

**Closed by artdude543** 2018-04-14 23:24 UTC
